import { Words } from '../models';

export const wordsEng: Words = {
    'A': {
        '3': [
            'ACE', 'ACT', 'ADD', 'ADO', 'AFT', 'AGE', 'AGO', 'AHA', 'AID', 'AIL', 'AIM', 'AIR', 'ALB', 'ALE', 'ALL', 'AMP', 'AND', 'ANT',
            'ANY', 'APE', 'APP', 'APT', 'ARC', 'ARE', 'ARK', 'ARM', 'ART', 'ASH', 'ASK', 'ASP', 'ASS', 'AVE', 'AYE', 'AWE', 'AWL', 'AWN',
            'AXE', 'AYE'
        ],
        '4': [
            'ABET', 'ABLE', 'ABLY', 'ABUT', 'ACHE', 'ACID', 'ACNE', 'ACRE', 'AERO', 'AFAR', 'AGED', 'AGOG', 'AHEM', 'AHOY', 'AIRY', 'AJAR',
            'AKIN', 'ALAS', 'ALGA', 'ALLY', 'ALMS', 'ALOE', 'ALSO', 'ALTO', 'ALUM', 'AMEN', 'AMID', 'AMOK', 'ANAL', 'ANEW', 'ANKH', 'ANON',
            'ANTE', 'ANUS', 'APEX', 'APSE', 'ARCH', 'AREA', 'ARIA', 'ARID', 'ARMS', 'ARMY', 'ARSE', 'ARTS', 'ARTY', 'ASHY', 'ATOM', 'ATOP',
            'AUNT', 'AURA', 'AUTO', 'AVID', 'AVOW', 'AWAY', 'AWRY', 'AXIS'
        ],
        '5': [
            'ABACK', 'ABASE', 'ABASH', 'ABATE', 'ABBEY', 'ABBOT', 'ABHOR', 'ABIDE', 'ABODE', 'ABORT', 'ABOUT', 'ABOVE', 'ABUSE', 'ABYSS',
            'ACORN', 'ACRID', 'ACTOR', 'ACUTE', 'ADAGE', 'ADAPT', 'ADDED', 'ADDER', 'ADDLE', 'ADEPT', 'ADIEU', 'ADMAN', 'ADMIN', 'ADMIT',
            'ADOBE', 'ADOPT', 'ADORE', 'ADORN', 'ADULT', 'AEGIS', 'AFFIX', 'AFIRE', 'AFOOT', 'AFOUL', 'AFTER', 'AGAIN', 'AGAPE', 'AGATE',
            'AGENT', 'AGGRO', 'AGILE', 'AGLOW', 'AGONY', 'AGREE', 'AHEAD', 'AISLE', 'ALACK', 'ALARM', 'ALBUM', 'ALDER', 'ALERT', 'ALIAS',
            'ALIBI', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLAY', 'ALLEY', 'ALLOT', 'ALLOW', 'ALLOY', 'ALOFT', 'ALONE', 'ALONG', 'ALOOF',
            'ALOUD', 'ALPHA', 'ALTAR', 'ALTER', 'AMASS', 'AMAZE', 'AMBER', 'AMBIT', 'AMBLE', 'AMEND', 'AMISS', 'AMITY', 'AMONG', 'AMPLE',
            'AMPLY', 'AMUSE', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'ANGST', 'ANIME', 'ANISE', 'ANKLE', 'ANNEX', 'ANNOY', 'ANNUL', 'ANVIL',
            'AORTA', 'APACE', 'APART', 'APHID', 'APISH', 'APPAL', 'APPLE', 'APPLY', 'APRON', 'ARENA', 'ARGON', 'ARGOT', 'ARGUE', 'ARIES',
            'ARISE', 'ARMED', 'AROMA', 'ARRAY', 'ARROW', 'ARSON', 'ARTSY', 'ASCOT', 'ASHEN', 'ASHES', 'ASIDE', 'ASKEW', 'ASPEN', 'ASPIC',
            'ASSET', 'ASTER', 'ASTIR', 'ATLAS', 'ATOLL', 'ATONE', 'ATTIC', 'AUDIO', 'AUGHT', 'AUDIT', 'AUGUR', 'AURAL', 'AVAIL', 'AVERT',
            'AVOID', 'AWAIT', 'AWAKE', 'AWARD', 'AWARE', 'AWASH', 'AWFUL', 'AXIAL', 'AXIOM', 'AZURE'
        ],
        '6': [
            'ABACUS', 'ABBESS', 'ABDUCT', 'ABJECT', 'ABJURE', 'ABLAZE', 'ABOARD', 'ABOUND', 'ABRADE', 'ABROAD', 'ABRUPT', 'ABSEIL',
            'ABSENT', 'ABSORB', 'ABSURD', 'ACACIA', 'ACCEDE', 'ACCENT', 'ACCEPT', 'ACCESS', 'ACCORD', 'ACCOST', 'ACCRUE', 'ACCUSE',
            'ACETIC', 'ACIDIC', 'ACORNS', 'ACQUIT', 'ACROSS', 'ACTING', 'ACTION', 'ACTIVE', 'ACTUAL', 'ACUITY', 'ACUMEN', 'ADAGIO',
            'ADDICT', 'ADDING', 'ADDLED', 'ADDUCE', 'ADHERE', 'ADJOIN', 'ADJURE', 'ADJUST', 'ADMIRE', 'ADRIFT', 'ADROIT', 'ADSORB',
            'ADVENT', 'ADVERB', 'ADVERT', 'ADVICE', 'ADVISE', 'AERATE', 'AERIAL', 'AETHER', 'AFFAIR', 'AFFECT', 'AFFIRM', 'AFFORD',
            'AFFRAY', 'AFGHAN', 'AFIELD', 'AFLAME', 'AFLOAT', 'AFRAID', 'AFRESH', 'AFTERS', 'AGEING', 'AGEISM', 'AGEIST', 'AGENCY',
            'AGENDA', 'AGHAST', 'AGREED', 'AIKIDO', 'AIRBAG', 'AIRBED', 'AIRBUS', 'AIRGUN', 'AIRILY', 'AIRING', 'AIRMAN', 'AIRWAY',
            'AKIMBO', 'ALBEIT', 'ALBINO', 'ALCOVE', 'ALIGHT', 'ALLEGE', 'ALLIED', 'ALLUDE', 'ALLURE', 'ALMOND', 'ALMOST', 'ALPACA',
            'ALPINE', 'ALWAYS', 'AMAZED', 'AMBUSH', 'AMENDS', 'AMIDST', 'AMOEBA', 'AMORAL', 'AMOUNT', 'AMPERE', 'AMPULE', 'AMULET',
            'ANCHOR', 'ANEMIA', 'ANEMIC', 'ANGLER', 'ANIMAL', 'ANKLET', 'ANOINT', 'ANNALS', 'ANNEAL', 'ANNUAL', 'ANORAK', 'ANSWER',
            'ANTHEM', 'ANTHER', 'ANTICS', 'ANTLER', 'ANTRUM', 'ANYHOW', 'ANYONE', 'ANYWAY', 'APATHY', 'APHTHA', 'APIARY', 'APIECE',
            'APLOMB', 'APOGEE', 'APPALL', 'APPEAL', 'APPEAR', 'APPEND', 'APPLET', 'ARABLE', 'ARBOUR', 'ARCADE', 'ARCANE', 'ARCHER',
            'ARCTIC', 'ARDENT', 'ARDOUR', 'ARGENT', 'ARMADA', 'ARMFUL', 'ARMLET', 'ARMOUR', 'ARMPIT', 'AROUND', 'AROUSE', 'ARRACK',
            'ARRANT', 'ARREST', 'ARRIVE', 'ARTERY', 'ARTFUL', 'ARTIST', 'ASCEND', 'ASCENT', 'ASHORE', 'ASLANT', 'ASLEEP', 'ASPECT',
            'ASPIRE', 'ASSAIL', 'ASSENT', 'ASSERT', 'ASSESS', 'ASSIGN', 'ASSIST', 'ASSORT', 'ASSUME', 'ASSURE', 'ASTERN', 'ASTHMA',
            'ASTRAL', 'ASTRAY', 'ASTUTE', 'ASYLUM', 'ATOMIC', 'ATONAL', 'ATTACH', 'ATTACK', 'ATTAIN', 'ATTEND', 'ATTEST', 'ATTIRE',
            'ATTUNE', 'AUBURN', 'AUGURY', 'AUGUST', 'AUNTIE', 'AURIST', 'AURORA', 'AUTHOR', 'AUTISM', 'AUTIST', 'AUTUMN', 'AVATAR',
            'AVENGE', 'AVERSE', 'AVIARY', 'AVOWAL', 'AWAKEN', 'AWHILE', 'AWNING', 'AXEMAN', 'AZALEA'
        ],
        '7': [
            'ABANDON', 'ABDOMEN', 'ABETTOR', 'ABILITY', 'ABOLISH', 'ABREAST', 'ABRIDGE', 'ABSCOND', 'ABSENCE', 'ABSOLVE', 'ABSTAIN',
            'ABUSIVE', 'ABYSMAL', 'ACADEMY', 'ACCLAIM', 'ACCOUNT', 'ACCRUAL', 'ACCUSED', 'ACERBIC', 'ACETATE', 'ACETIFY', 'ACHIEVE',
            'ACIDITY', 'ACOLYTE', 'ACQUIRE', 'ACTRESS', 'ACQUIRE', 'ACREAGE', 'ACROBAT', 'ACRONYM', 'ACTRESS', 'ACTUARY', 'ACTUATE',
            'ADAMANT', 'ADAPTER', 'ADDRESS', 'ADJOURN', 'ADJUDGE', 'ADJUNCT', 'ADMIRAL', 'ADULATE', 'ADVANCE', 'ADVERSE', 'ADVISOR',
            'AEROBIC', 'AEROSOL', 'AFFABLE', 'AFFLICT', 'AFFRONT', 'AGAINST', 'AGELESS', 'AGILITY', 'AGITATE', 'AGONIZE', 'AGROUND',
            'AILMENT', 'AIMLESS', 'AIRCREW', 'AIRDROP', 'AIRFARE', 'AIRFLOW', 'AIRLESS', 'AIRLINE', 'AIRLOCK', 'AIRMAIL', 'AIRPORT',
            'AIRSHIP', 'AIRSICK', 'AIRTIME', 'AIRWAYS', 'ALBUMIN', 'ALCOHOL', 'ALFALFA', 'ALGEBRA', 'ALIMONY', 'ALIQUOT', 'ALLEGED',
            'ALLERGY', 'ALREADY', 'ALUMNUS', 'AMALGAM', 'AMATEUR', 'AMATORY', 'AMAZING', 'AMBIENT', 'AMIABLE', 'AMONGST', 'AMOROUS',
            'AMPLIFY', 'AMPUTEE', 'AMUSING', 'ANAEMIA', 'ANAEMIC', 'ANAGRAM', 'ANALOGY', 'ANALYSE', 'ANALYST', 'ANALYZE', 'ANATOMY',
            'ANCHOVY', 'ANCIENT', 'ANEMONE', 'ANGLING', 'ANGRILY', 'ANGUISH', 'ANGULAR', 'ANIMATE', 'ANIMISM', 'ANISEED', 'ANNOYED',
            'ANNUITY', 'ANNULAR', 'ANNULUS', 'ANOMALY', 'ANOTHER', 'ANTENNA', 'ANTHILL', 'ANTIGEN', 'ANTIQUE', 'ANTONYM', 'ANXIETY',
            'ANXIOUS', 'ANYBODY', 'APHASIA', 'APHASIC', 'APLENTY', 'APOLOGY', 'APOSTLE', 'APPAREL', 'APPEASE', 'APPLAUD', 'APPLIED',
            'APPOINT', 'APPRIZE', 'APPROVE', 'APRICOT', 'APTNESS', 'AQUATIC', 'ARBITER', 'ARCHAIC', 'ARCHERY', 'ARCHIVE', 'ARCHWAY',
            'ARDUOUS', 'ARIDITY', 'ARMHOLE', 'ARMOURY', 'ARMREST', 'AROUSAL', 'ARRAIGN', 'ARRANGE', 'ARREARS', 'ARRIVAL', 'ARSENAL',
            'ARSENIC', 'ARTICLE', 'ARTISAN', 'ARTISTE', 'ARTLESS', 'ARTWORK', 'ASCETIC', 'ASCRIBE', 'ASEPTIC', 'ASEXUAL', 'ASHAMED',
            'ASHTRAY', 'ASININE', 'ASKANCE', 'ASPERSE', 'ASPHALT', 'ASPIRIN', 'ASSAULT', 'ASSHOLE', 'ASSUAGE', 'ASTOUND', 'ASTRIDE',
            'ASUNDER', 'ATELIER', 'ATHEISM', 'ATHEIST', 'ATHLETE', 'ATHWART', 'ATOMIZE', 'ATROPHY', 'ATTACHE', 'ATTEMPT', 'ATTRACT',
            'AUCTION', 'AUDIBLE', 'AUDITOR', 'AUGMENT', 'AUREOLE', 'AURICLE', 'AUSTERE', 'AUTOPSY', 'AVARICE', 'AVENGER', 'AVERAGE',
            'AVIATOR', 'AVIDITY', 'AVOCADO', 'AWESOME', 'AWFULLY', 'AWKWARD'
        ]
    },
    'B': {
        '3': [
            'BAA', 'BAD', 'BAG', 'BAH', 'BAN', 'BAP', 'BAR', 'BAT', 'BAY', 'BED', 'BEE', 'BEG', 'BET', 'BEY', 'BIB', 'BID', 'BIG', 'BIN',
            'BIT', 'BOA', 'BOB', 'BOG', 'BOO', 'BOP', 'BOT', 'BOW', 'BOX', 'BOY', 'BRA', 'BUB', 'BUD', 'BUG', 'BUM', 'BUN', 'BUR', 'BUS',
            'BUT', 'BUY', 'BYE'
        ],
        '4': [
            'BABA', 'BABE', 'BABY', 'BACK', 'BAGS', 'BAIL', 'BAIT', 'BAKE', 'BALD', 'BALE', 'BALK', 'BALL', 'BALM', 'BAND', 'BANE', 'BANG',
            'BANK', 'BARB', 'BARD', 'BARE', 'BARK', 'BARM', 'BARN', 'BASE', 'BASH', 'BASK', 'BASS', 'BAST', 'BATH', 'BATS', 'BAUD', 'BAWL',
            'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT', 'BEAU', 'BECK', 'BELL', 'BEND', 'BEEF', 'BEEP', 'BEER', 'BEET', 'BELL', 'BELT',
            'BEND', 'BENT', 'BERK', 'BEST', 'BETA', 'BEVY', 'BIAS', 'BIDE', 'BIER', 'BIFF', 'BIKE', 'BILE', 'BILL', 'BIND', 'BINT', 'BIRD',
            'BIRO', 'BITE', 'BITT', 'BLAB', 'BLAH', 'BLIP', 'BLOB', 'BLOC', 'BLOT', 'BLOW', 'BLUB', 'BLUE', 'BLUR', 'BOAR', 'BOAT', 'BODE',
            'BODY', 'BOIL', 'BOLD', 'BOLE', 'BOLL', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BONK', 'BONY', 'BOOB', 'BOOK', 'BOOM', 'BOON', 'BOOR',
            'BOOT', 'BORA', 'BORE', 'BORN', 'BOSH', 'BOSS', 'BOTH', 'BOUT', 'BOWL', 'BRAE', 'BRAG', 'BRAN', 'BRAT', 'BRAY', 'BREW', 'BRIM',
            'BROW', 'BRUT', 'BUCK', 'BUFF', 'BULB', 'BULK', 'BULL', 'BUMP', 'BUND', 'BUNG', 'BUNK', 'BUNT', 'BUOY', 'BURK', 'BURN', 'BURP',
            'BURR', 'BURY', 'BUSH', 'BUSK', 'BUST', 'BUSY', 'BUTT', 'BUZZ', 'BYTE'
        ],
        '5': [
            'BABEL', 'BACON', 'BADGE', 'BADLY', 'BAGEL', 'BAGGY', 'BAIZE', 'BAKED', 'BAKER', 'BALER', 'BALLS', 'BALLY', 'BALMY', 'BANAL',
            'BANDY', 'BANGS', 'BANJO', 'BARDE', 'BARGE', 'BARMY', 'BARON', 'BASIC', 'BASIN', 'BASIS', 'BASSO', 'BASTE', 'BATHE', 'BATCH',
            'BATED', 'BATHE', 'BATHS', 'BATIK', 'BATON', 'BATTY', 'BAULK', 'BAWDY', 'BAYOU', 'BAZOO', 'BEACH', 'BEADS', 'BEADY', 'BEARD',
            'BEAST', 'BEDIM', 'BEECH', 'BEEFY', 'BEERY', 'BEFIT', 'BEGIN', 'BEIGE', 'BEING', 'BELCH', 'BELIE', 'BELLE', 'BELLS', 'BELLY',
            'BELOW', 'BENCH', 'BENDS', 'BENDY', 'BERRY', 'BERTH', 'BESET', 'BESOM', 'BEVEL', 'BEVVY', 'BIDET', 'BIGOT', 'BIJOU', 'BIKER',
            'BILGE', 'BINGE', 'BINGO', 'BIPED', 'BIRCH', 'BIRTH', 'BITCH', 'BITTY', 'BLACK', 'BLADE', 'BLAME', 'BLAND', 'BLANK', 'BLARE',
            'BLASE', 'BLAST', 'BLAZE', 'BLEAK', 'BLEAT', 'BLEED', 'BLEEP', 'BLEND', 'BLESS', 'BLIMP', 'BLIND', 'BLINK', 'BLISS', 'BLITZ',
            'BLOAT', 'BLOCK', 'BLOKE', 'BLOND', 'BLOOD', 'BLOOM', 'BLOWY', 'BLUES', 'BLUFF', 'BLUNT', 'BLURB', 'BLURT', 'BLUSH', 'BOARD',
            'BOAST', 'BOBBY', 'BODGE', 'BOFFO', 'BOGEY', 'BOGGY', 'BOGUS', 'BONER', 'BONNY', 'BONUS', 'BOOBY', 'BOOKS', 'BOOST', 'BOOTH',
            'BOOTS', 'BOOTY', 'BOOZE', 'BOOZY', 'BORED', 'BORNE', 'BORON', 'BOSOM', 'BOSSY', 'BOSUN', 'BOTCH', 'BOUGH', 'BOUND', 'BOWEL',
            'BOWER', 'BOWLS', 'BOXER', 'BRACE', 'BRAID', 'BRAIN', 'BRAKE', 'BRAND', 'BRASH', 'BRASS', 'BRAVE', 'BRAVO', 'BRAWL', 'BRAWN',
            'BREAD', 'BREAK', 'BREED', 'BRIAR', 'BRIBE', 'BRICK', 'BRIDE', 'BRIEF', 'BRIER', 'BRILL', 'BRINE', 'BRING', 'BRINK', 'BRISK',
            'BROAD', 'BROIL', 'BROKE', 'BROOD', 'BROOK', 'BROOM', 'BROTH', 'BROWN', 'BRUIN', 'BRUNT', 'BRUSH', 'BRUTE', 'BUDDY', 'BUDGE',
            'BUGGY', 'BUGLE', 'BUILD', 'BULGE', 'BULKY', 'BULLY', 'BUMPY', 'BUNCH', 'BUNCO', 'BUNNY', 'BURLY', 'BURRO', 'BURST', 'BUSHY',
            'BUSTY', 'BUTTY', 'BUXOM', 'BUYER', 'BYLAW', 'BYWAY'
        ],
        '6': [
            'BABBLE', 'BABOON', 'BACKER', 'BACKUP', 'BADDIE', 'BADGER', 'BAFFLE', 'BAGFUL', 'BAILER', 'BAILEY', 'BAKERY', 'BAKING',
            'BALDLY', 'BALLAD', 'BALLET', 'BALLOT', 'BALLSY', 'BALSAM', 'BAMBOO', 'BANANA', 'BANDIT', 'BANGER', 'BANGLE', 'BANISH',
            'BANKER', 'BANNED', 'BANNER', 'BANTAM', 'BANTER', 'BAOBAB', 'BARBED', 'BARBEL', 'BARBER', 'BARELY', 'BARGEE', 'BARIUM',
            'BARKER', 'BARLEY', 'BARMAN', 'BARNEY', 'BARONY', 'BARQUE', 'BARREL', 'BARREN', 'BARROW', 'BARTER', 'BASALT', 'BASELY',
            'BASKET', 'BASSET', 'BASQUE', 'BATATA', 'BATHER', 'BATMAN', 'BATTEN', 'BATTER', 'BATTLE', 'BAUBLE', 'BAZAAR', 'BEACON',
            'BEADLE', 'BEAGLE', 'BEAKER', 'BEARER', 'BEATEN', 'BEATER', 'BEAUTY', 'BEAVER', 'BECKON', 'BECOME', 'BEDAUB', 'BEDECK',
            'BEDLAM', 'BEDPAN', 'BEEPER', 'BEETLE', 'BEFALL', 'BEFORE', 'BEFOUL', 'BEGGAR', 'BEGONE', 'BEHALF', 'BEHAVE', 'BEHEAD',
            'BEHEST', 'BEHIND', 'BEHOLD', 'BELFRY', 'BELIEF', 'BELLOW', 'BELONG', 'BELUGA', 'BEMOAN', 'BENIGN', 'BERATE', 'BEREFT',
            'BESIDE', 'BESTIR', 'BESTOW', 'BETHEL', 'BETIDE', 'BETRAY', 'BETTER', 'BETTOR', 'BEWAIL', 'BEWARE', 'BEYOND', 'BIASED',
            'BICARB', 'BICEPS', 'BICKER', 'BIDDER', 'BIGAMY', 'BIKINI', 'BILLET', 'BILLOW', 'BINARY', 'BINDER', 'BINMAN', 'BIOGAS',
            'BIOPSY', 'BIRDER', 'BIRDIE', 'BISECT', 'BISHOP', 'BISQUE', 'BISTRO', 'BITCHY', 'BITING', 'BITMAP', 'BITTER', 'BLANCH',
            'BLAZER', 'BLAZON', 'BLEACH', 'BLENCH', 'BLIGHT', 'BLIMEY', 'BLITHE', 'BLONDE', 'BLOODY', 'BLOTCH', 'BLOUSE', 'BLOWER',
            'BLOWZY', 'BLUISH', 'BOARDS', 'BOATER', 'BOBBIN', 'BOBCAT', 'BODICE', 'BODILY', 'BOFFIN', 'BOGGLE', 'BOILED', 'BOILER',
            'BOLERO', 'BOLLIX', 'BOMBER', 'BONBON', 'BONDED', 'BONNET', 'BONSAI', 'BOOGIE', 'BOOHOO', 'BOOKED', 'BOOMER', 'BOOTED',
            'BOOTEE', 'BORDER', 'BORING', 'BORROW', 'BORSCH', 'BOSOMY', 'BOTANY', 'BOTCHY', 'BOTFLY', 'BOTHER', 'BOTTLE', 'BOTTOM',
            'BOUGIE', 'BOUNCE', 'BOUNCY', 'BOUNDS', 'BOUNTY', 'BOURSE', 'BOVINE', 'BOWING', 'BOWLER', 'BOXCAR', 'BOXERS', 'BOXFUL',
            'BOXING', 'BOYISH', 'BRACES', 'BRAINY', 'BRANCH', 'BRANDY', 'BRASSY', 'BRAWNY', 'BRAZEN', 'BREACH', 'BREAST', 'BREATH',
            'BREECH', 'BREEZE', 'BREEZY', 'BREWER', 'BRIBER', 'BRIDAL', 'BRIDLE', 'BRIDGE', 'BRIEFS', 'BRIGHT', 'BROACH', 'BROGUE',
            'BROKER', 'BRONCO', 'BRONZE', 'BROOCH', 'BROODY', 'BROWSE', 'BRUISE', 'BRUNCH', 'BRUTAL', 'BUBBLE', 'BUBBLY', 'BUCKET',
            'BUCKLE', 'BUDGET', 'BUDGIE', 'BUFFER', 'BUFFET', 'BUGGER', 'BULLET', 'BUMBLE', 'BUMMER', 'BUMPER', 'BUNDLE', 'BUNGLE',
            'BUNION', 'BUNKER', 'BUNKUM', 'BURBLE', 'BURDEN', 'BUREAU', 'BURGER', 'BURGLE', 'BURIAL', 'BURNER', 'BURROW', 'BURSAR',
            'BUSHEL', 'BUSILY', 'BUSKER', 'BUSTER', 'BUSTLE', 'BUTANE', 'BUTLER', 'BUTTER', 'BUTTON', 'BUYING', 'BUYOUT', 'BUZZER',
            'BYGONE', 'BYPASS', 'BYPATH', 'BYPLAY', 'BYPLOT', 'BYROAD', 'BYWORD'
        ],
        '7': [
            'BABYISH', 'BABYSIT', 'BACKING', 'BACKLOG', 'BADNESS', 'BAGGAGE', 'BAGGING', 'BAGPIPE', 'BAILIFF', 'BAILOUT', 'BAKLAVA',
            'BALANCE', 'BALCONY', 'BALDING', 'BALEFUL', 'BALLAST', 'BALLOON', 'BALONEY', 'BANANAS', 'BANDAGE', 'BANDBOX', 'BANDING',
            'BANEFUL', 'BANKING', 'BANNOCK', 'BANQUET', 'BANSHEE', 'BAPTISM', 'BAPTIST', 'BAPTIZE', 'BARGAIN', 'BARKING', 'BARMAID',
            'BARONET', 'BAROQUE', 'BARRACK', 'BARRAGE', 'BARRIER', 'BARRING', 'BASEMAN', 'BASHFUL', 'BASSIST', 'BASSOON', 'BASTARD',
            'BASTION', 'BATHING', 'BATHTUB', 'BATISTE', 'BATTERY', 'BATWING', 'BAUXITE', 'BAYONET', 'BAYWOOD', 'BAZOOKA', 'BEAMING',
            'BEANBAG', 'BEARDED', 'BEARING', 'BEARISH', 'BEASTLY', 'BEATBOX', 'BEATIFY', 'BEATING', 'BECAUSE', 'BEDDING', 'BEDIZEN',
            'BEDPOST', 'BEDROCK', 'BEDROLL', 'BEDROOM', 'BEDSIDE', 'BEDSORE', 'BEDTIME', 'BEEHIVE', 'BEELINE', 'BEESWAX', 'BEGGARY',
            'BEGONIA', 'BEGUILE', 'BELATED', 'BELIEVE', 'BELLBOY', 'BELLHOP', 'BELLOWS', 'BELOVED', 'BELTWAY', 'BENEATH', 'BENEFIT',
            'BENZENE', 'BENZINE', 'BENZOLE', 'BEQUEST', 'BEREAVE', 'BERSERK', 'BESEECH', 'BESIDES', 'BESIEGE', 'BESMEAR', 'BESPEAK',
            'BESPOKE', 'BESTIAL', 'BESTREW', 'BETOKEN', 'BETROTH', 'BETTERS', 'BETTING', 'BETWEEN', 'BEWITCH', 'BICYCLE', 'BIDDING',
            'BIFOCAL', 'BISCUIT', 'BIGHEAD', 'BIGNESS', 'BIGOTED', 'BIGOTRY', 'BILIOUS', 'BILLION', 'BINDERY', 'BINDING', 'BIOLOGY',
            'BIOMASS', 'BIONICS', 'BIOTECH', 'BIPLANE', 'BIPOLAR', 'BIRDMAN', 'BISCUIT', 'BISMUTH', 'BITTERN', 'BITTERS', 'BITUMEN',
            'BIVOUAC', 'BIZARRE', 'BLABBER', 'BLACKEN', 'BLACKLY', 'BLADDER', 'BLADING', 'BLANKET', 'BLARNEY', 'BLASTED', 'BLATANT',
            'BLATHER', 'BLEEDER', 'BLEEPER', 'BLEMISH', 'BLENDER', 'BLESSED', 'BLETHER', 'BLISTER', 'BLINDER', 'BLISTER', 'BLOATER',
            'BLOCKED', 'BLOCKER', 'BLOOMER', 'BLOOPER', 'BLOSSOM', 'BLOTCHY', 'BLOTTER', 'BLOWGUN', 'BLUBBER', 'BLUNDER', 'BLUNTLY',
            'BLURRED', 'BLUSHER', 'BLUSTER', 'BOARDER', 'BOATING', 'BOATMAN', 'BOBSLED', 'BOBTAIL', 'BODYBAG', 'BOILING', 'BOLETUS',
            'BOLLARD', 'BOLONEY', 'BOLSTER', 'BOMBARD', 'BOMBAST', 'BOMBING', 'BONANZA', 'BONDAGE', 'BONDING', 'BONFIRE', 'BONKERS',
            'BOOKEND', 'BOOKING', 'BOOKISH', 'BOOKLET', 'BOORISH', 'BOOSTER', 'BOOTLEG', 'BOREDOM', 'BOROUGH', 'BORSTAL', 'BOTANIC',
            'BOTTLER', 'BOULDER', 'BOUNCER', 'BOUNDEN', 'BOUQUET', 'BOURBON', 'BOWLFUL', 'BOWLING', 'BOWSHOT', 'BOYCOTT', 'BOYHOOD',
            'BRACING', 'BRACKET', 'BRAMBLE', 'BRAVADO', 'BRAVELY', 'BRAVERY', 'BREADED', 'BREADTH', 'BREAKER', 'BREAKUP', 'BREATHE',
            'BREEDER', 'BREVITY', 'BREWERY', 'BREWPUB', 'BRIBERY', 'BRIGADE', 'BRIGAND', 'BRIGHTS', 'BRIMFUL', 'BRIOCHE', 'BRIQUET',
            'BRISKET', 'BRISTLE', 'BRISTLY', 'BRITTLE', 'BROADEN', 'BROADLY', 'BROCADE', 'BROILER', 'BROKING', 'BROMIDE', 'BROODER',
            'BROTHEL', 'BROTHER', 'BROWNIE', 'BROWSER', 'BRUSQUE', 'BRUTISH', 'BUCKEYE', 'BUCKSAW', 'BUCOLIC', 'BUFFALO', 'BUFFOON',
            'BUGABOO', 'BUGBEAR', 'BUILDER', 'BUILDUP', 'BULBOUS', 'BULGING', 'BULIMIA', 'BULIMIC', 'BULLDOG', 'BULLION', 'BULLISH',
            'BULLOCK', 'BULRUSH', 'BULWARK', 'BUMPKIN', 'BUNDLED', 'BUNTING', 'BUOYANT', 'BURDOCK', 'BURGEON', 'BURGESS', 'BURGHER',
            'BURGLAR', 'BURNING', 'BURNOUT', 'BURRITO', 'BURSARY', 'BUSHMAN', 'BUSTARD', 'BUTCHER', 'BUTTERY', 'BUTTONS', 'BUZZARD',
            'BYGONES'
        ]
    },
    'C': {
        '3': [
            'CAB', 'CAD', 'CAM', 'CAN', 'CAP', 'CAR', 'CAT', 'CAW', 'CEP', 'COB', 'COD', 'COG', 'CON', 'COO', 'COP', 'COT', 'COW', 'COX',
            'COY', 'CRY', 'CUB', 'CUD', 'CUE', 'CUP', 'CUR', 'CUT'
        ],
        '4': [
            'CAFE', 'CAGE', 'CAKE', 'CALF', 'CALL', 'CALM', 'CAMP', 'CANE', 'CANT', 'CAPE', 'CARD', 'CARE', 'CARP', 'CART', 'CASE', 'CASH',
            'CASK', 'CAST', 'CAVE', 'CEDE', 'CELL', 'CENT', 'CERT', 'CLAN', 'CHAP', 'CHAR', 'CHAT', 'CHEF', 'CHEW', 'CHIC', 'CHIN', 'CHIP',
            'CHIT', 'CHOC', 'CHOP', 'CHOW', 'CHUG', 'CHUM', 'CIAO', 'CITE', 'CITY', 'CLAD', 'CLAM', 'CLAN', 'CLAP', 'CLAW', 'CLAY', 'CLEF',
            'CLIP', 'CLOD', 'CLOG', 'CLOP', 'CLOT', 'CLOY', 'CLUB', 'CLUE', 'COAL', 'COAT', 'COAX', 'COCA', 'COCK', 'CODA', 'CODE', 'COIF',
            'COIL', 'COIN', 'COKE', 'COLD', 'COLE', 'COLT', 'COMA', 'COMB', 'COME', 'CONE', 'CONK', 'CONY', 'COOK', 'COOL', 'COON', 'COOP',
            'COOT', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORM', 'CORN', 'COSH', 'COST', 'COSY', 'COUP', 'COVE', 'COWL', 'COZY', 'CRAB',
            'CRAG', 'CRAM', 'CRAP', 'CRAW', 'CRED', 'CREW', 'CRIB', 'CROP', 'CROW', 'CRUD', 'CRUX', 'CUBE', 'CUFF', 'CULL', 'CULT', 'CURB',
            'CURD', 'CURE', 'CURL', 'CUSP', 'CUSS', 'CUTE', 'CYAN', 'CYST', 'CZAR'
        ],
        '5': [
            'CABBY', 'CABIN', 'CABLE', 'CACAO', 'CACHE', 'CADDY', 'CADET', 'CADGE', 'CADRE', 'CAGEY', 'CALVE', 'CALYX', 'CAMEL', 'CAMEO',
            'CANAL', 'CANDY', 'CANNY', 'CANOE', 'CANON', 'CANTO', 'CAPER', 'CAPON', 'CARAT', 'CARDS', 'CARER', 'CARET', 'CARGO', 'CAROB',
            'CAROL', 'CAROM', 'CARRY', 'CARVE', 'CASTE', 'CATCH', 'CATER', 'CATTY', 'CAULK', 'CAUSE', 'CAVER', 'CAVIL', 'CEASE', 'CECUM',
            'CEDAR', 'CELLO', 'CENSE', 'CHAFE', 'CHAFF', 'CHAIN', 'CHAIR', 'CHALK', 'CHAMP', 'CHANT', 'CHAOS', 'CHARD', 'CHARM', 'CHART',
            'CHARY', 'CHASE', 'CHASM', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEEP', 'CHEER', 'CHESS', 'CHEST', 'CHEWY', 'CHICK', 'CHIDE',
            'CHIEF', 'CHILD', 'CHILI', 'CHILL', 'CHIME', 'CHIMP', 'CHINA', 'CHINE', 'CHINK', 'CHIPS', 'CHIRP', 'CHIVE', 'CHIVY', 'CHOCK',
            'CHOIR', 'CHOKE', 'CHOKY', 'CHOPS', 'CHORD', 'CHORE', 'CHUCK', 'CHUMP', 'CHUNK', 'CHURL', 'CHURN', 'CHUTE', 'CIDER', 'CIGAR',
            'CINCH', 'CIRCA', 'CISSY', 'CIVET', 'CIVIC', 'CIVIL', 'CLACK', 'CLAIM', 'CLAMP', 'CLANG', 'CLANK', 'CLASH', 'CLASP', 'CLASS',
            'CLEAN', 'CLEAR', 'CLEAT', 'CLEFT', 'CLERK', 'CLICK', 'CLIFF', 'CLIMB', 'CLIME', 'CLINE', 'CLING', 'CLINK', 'CLOAK', 'CLOCK',
            'CLONE', 'CLOSE', 'CLOTH', 'CLOUD', 'CLOUT', 'CLOVE', 'CLOWN', 'CLUBS', 'CLUCK', 'CLUMP', 'COACH', 'COAST', 'COBRA', 'COCKY',
            'COCOA', 'CODED', 'CODEX', 'COLIC', 'COLON', 'COLOR', 'COMBO', 'COMER', 'COMET', 'COMFY', 'COMIC', 'COMMA', 'CONCH', 'CONDO',
            'CONEY', 'CONGA', 'CONIC', 'COPSE', 'CORAL', 'CORDS', 'CORER', 'CORGI', 'CORNY', 'CORPS', 'COSTS', 'COUCH', 'COUGH', 'COULD',
            'COUNT', 'COUPE', 'COURT', 'COVER', 'COVET', 'COWER', 'COYPU', 'CRACK', 'CRAFT', 'CRAMP', 'CRANE', 'CRANK', 'CRAPE', 'CRASH',
            'CRASS', 'CRATE', 'CRAVE', 'CRAWL', 'CRAZE', 'CRAZY', 'CREAK', 'CREAM', 'CREDO', 'CREED', 'CREEK', 'CREEL', 'CREEP', 'CREME',
            'CREPE', 'CRESS', 'CREST', 'CRICK', 'CRIER', 'CRIME', 'CRISP', 'CROAK', 'CROCK', 'CROFT', 'CRONE', 'CRONY', 'CROOK', 'CROON',
            'CROSS', 'CROUP', 'CROWD', 'CROWN', 'CRUDE', 'CRUEL', 'CRUET', 'CRUMB', 'CRUSE', 'CRUSH', 'CRUST', 'CRYPT', 'CUBIC', 'CUFFS',
            'CUMIN', 'CURIO', 'CURLY', 'CURRY', 'CURSE', 'CURVE', 'CURVY', 'CUSHY', 'CUTIE', 'CUTUP', 'CYBER', 'CYCLE', 'CYDER', 'CYNIC'
        ],
        '6': [
            'CABMAN', 'CACKLE', 'CACTUS', 'CADDIE', 'CADGER', 'CAFTAN', 'CAJOLE', 'CALICO', 'CALIPH', 'CALLER', 'CALLOW', 'CAMERA',
            'CAMPER', 'CAMPUS', 'CANAPE', 'CANARD', 'CANARY', 'CANCAN', 'CANCEL', 'CANCER', 'CANDID', 'CANDLE', 'CANINE', 'CANKER',
            'CANNED', 'CANNON', 'CANNOT', 'CANOLA', 'CANOPY', 'CANTER', 'CANTON', 'CANTOR', 'CANVAS', 'CANYON', 'CAPTOR', 'CARAFE',
            'CARBON', 'CARDER', 'CAREEN', 'CAREER', 'CARESS', 'CARIES', 'CARNAL', 'CARNEY', 'CARPET', 'CARREL', 'CARROT', 'CARTEL',
            'CARTER', 'CARTON', 'CARVER', 'CASHEW', 'CASING', 'CASINO', 'CASKET', 'CASTER', 'CASTLE', 'CASTOR', 'CASUAL', 'CATCHY',
            'CATKIN', 'CATNAP', 'CATTLE', 'CAUCUS', 'CAUDAL', 'CAUSAL', 'CAVEAT', 'CAVERN', 'CAVIAR', 'CAVITY', 'CAVORT', 'CELERY',
            'CELLAR', 'CEMENT', 'CENSER', 'CENSOR', 'CENSUS', 'CENTER', 'CENTRE', 'CEREAL', 'CERISE', 'CERVIX', 'CHAISE', 'CHALET',
            'CHALKY', 'CHANCE', 'CHANCY', 'CHANGE', 'CHANTY', 'CHAPEL', 'CHARGE', 'CHARTS', 'CHASER', 'CHASSE', 'CHASTE', 'CHATTY',
            'CHEAPO', 'CHEEKY', 'CHEERS', 'CHEERY', 'CHEESE', 'CHEESY', 'CHEQUE', 'CHERRY', 'CHERUB', 'CHICHI', 'CHILLI', 'CHILLY',
            'CHINCH', 'CHIPPY', 'CHIRPY', 'CHISEL', 'CHIVVY', 'CHOICE', 'CHOKED', 'CHOKER', 'CHOLER', 'CHOOSE', 'CHOOSY', 'CHORAL',
            'CHORUS', 'CHOSEN', 'CHROME', 'CHUBBY', 'CHUMMY', 'CHUNKY', 'CHURCH', 'CICADA', 'CINDER', 'CINEMA', 'CIPHER', 'CIRCLE',
            'CIRCUS', 'CITRON', 'CITRUS', 'CIVICS', 'CLAMMY', 'CLARET', 'CLASSY', 'CLAUSE', 'CLAYEY', 'CLEAVE', 'CLENCH', 'CLERGY',
            'CLERIC', 'CLEVER', 'CLICHE', 'CLIENT', 'CLIMAX', 'CLINCH', 'CLINIC', 'CLIQUE', 'CLOSED', 'CLOUDY', 'CLOSED', 'CLOSET',
            'CLOTHE', 'CLOUDY', 'CLOVER', 'CLUMSY', 'CLUTCH', 'COARSE', 'COATED', 'COBALT', 'COBBLE', 'COBWEB', 'COCKLE', 'COCOON',
            'CODDLE', 'CODIFY', 'CODING', 'COERCE', 'COEVAL', 'COFFEE', 'COFFER', 'COFFIN', 'COGENT', 'COGNAC', 'COHERE', 'COHORT',
            'COLOUR', 'COLUMN', 'COINER', 'COITUS', 'COLLAR', 'COLLIE', 'COLONY', 'COMBAT', 'COMBER', 'COMEDY', 'COMELY', 'COMICS',
            'COMING', 'COMITY', 'COMMIT', 'COMMON', 'COMPLY', 'CONCHA', 'CONCUR', 'CONDOM', 'CONDOR', 'CONFER', 'CONKER', 'CONSUL',
            'CONVEX', 'CONVEY', 'CONVOY', 'COOKED', 'COOKER', 'COOKIE', 'COOLER', 'COOLIE', 'COOPER', 'COPIER', 'COPPER', 'COPULA',
            'COQUET', 'CORBEL', 'CORDON', 'CORKED', 'CORKER', 'CORNEA', 'CORNED', 'CORNEL', 'CORNER', 'CORNET', 'CORONA', 'CORPSE',
            'CORPUS', 'CORRAL', 'CORSET', 'CORTEX', 'COSILY', 'COSINE', 'COSMIC', 'COSMOS', 'COSSET', 'COSTLY', 'COTTON', 'COUGAR',
            'COSTLY', 'COUGAR', 'COUNTY', 'COUPLE', 'COUPON', 'COURSE', 'COUSIN', 'COVERT', 'COWARD', 'COWBOY', 'COWMAN', 'COWPAT',
            'COWPOX', 'COWRIE', 'COYOTE', 'CRABBY', 'CRADLE', 'CRAFTY', 'CRAGGY', 'CRAMPS', 'CRANKY', 'CRANNY', 'CRAPPY', 'CRATER',
            'CRAVAT', 'CRAVEN', 'CRAYON', 'CRAZED', 'CREAKY', 'CREAMY', 'CREASE', 'CREATE', 'CRECHE', 'CREDIT', 'CREEPS', 'CREEPY',
            'CREOLE', 'CRETIN', 'CRIKEY', 'CRINGE', 'CRIPES', 'CRISIS', 'CRISPY', 'CRITIC', 'CROCUS', 'CROTCH', 'CROUCH', 'CRUDDY',
            'CRUISE', 'CRUMMY', 'CRUNCH', 'CRUSTY', 'CRUTCH', 'CRYING', 'CUBISM', 'CUBIST', 'CUCKOO', 'CUDDLE', 'CUDDLY', 'CUDGEL',
            'CUMBER', 'CUPFUL', 'CUPOLA', 'CURATE', 'CURDLE', 'CURFEW', 'CURLER', 'CURSED', 'CURSOR', 'CURTSY', 'CURVED', 'CUSSED',
            'CUSTOM', 'CUTLER', 'CUTLET', 'CUTOFF', 'CUTOUT', 'CUTTER', 'CUTTLE', 'CYBORG', 'CYCLIC', 'CYGNET', 'CYMBAL', 'CYPHER'
        ],
        '7': [
            'CABARET', 'CABINET', 'CABOOSE', 'CADAVER', 'CADENCE', 'CADENZA', 'CAESURA', 'CAGOULE', 'CAHOOTS', 'CAISSON', 'CALCIFY',
            'CALCIUM', 'CALDRON', 'CALIBRE', 'CALLBOX', 'CALLING', 'CALLOUS', 'CALORIE', 'CALUMNY', 'CALVARY', 'CAMBRIC', 'CAMPHOR',
            'CAMPING', 'CANASTA', 'CANDIED', 'CANDOUR', 'CANNING', 'CANTATA', 'CANTEEN', 'CANNULA', 'CAPABLE', 'CAPITAL', 'CAPRICE',
            'CAPSIZE', 'CAPSTAN', 'CAPSULE', 'CAPTAIN', 'CAPTION', 'CAPTIVE', 'CAPTURE', 'CARAMEL', 'CARAVAN', 'CARAWAY', 'CARBINE',
            'CARCASS', 'CARDIAC', 'CAREFUL', 'CARFARE', 'CARJACK', 'CARMINE', 'CARNAGE', 'CAROUSE', 'CARPORT', 'CARRIER', 'CARRION',
            'CARROTY', 'CARSICK', 'CARTOON', 'CARVERY', 'CASCADE', 'CASHIER', 'CASSAVA', 'CASSOCK', 'CASTING', 'CASTOFF', 'CATARRH',
            'CATCALL', 'CATCHER', 'CATCHUP', 'CATERER', 'CATSUIT', 'CATTAIL', 'CATWALK', 'CAUTION', 'CAVALRY', 'CAVEMAN', 'CAYENNE',
            'CEILIDH', 'CEILING', 'CELESTA', 'CELLIST', 'CAMBALO', 'CENSURE', 'CENTRAL', 'CENTURY', 'CERAMIC', 'CERTAIN', 'CERTIFY',
            'CERUMEN', 'CESSION', 'CESSPIT', 'CHAGRIN', 'CHALICE', 'CHAMBER', 'CHAMOIS', 'CHANCEL', 'CHANNEL', 'CHAOTIC', 'CHAPLET',
            'CHAPMAN', 'CHAPTER', 'CHARADE', 'CHARGED', 'CHARGER', 'CHARIOT', 'CHARITY', 'CHARMER', 'CHARRED', 'CHARTER', 'CHASSIS',
            'CHASTEN', 'CHATEAU', 'CHATTEL', 'CHATTER', 'CHEAPEN', 'CHEAPLY', 'CHECKED', 'CHECKUP', 'CHEDDAR', 'CHEERIO', 'CHEETAH',
            'CHEMISE', 'CHEMIST', 'CHERISH', 'CHEVRON', 'CHICKEN', 'CHICORY', 'CHIEFLY', 'CHIFFON', 'CHIGNON', 'CHILLER', 'CHIMERA',
            'CHIMNEY', 'CHINWAG', 'CHIPPER', 'CHIPSET', 'CHOKING', 'CHOLERA', 'CHOPPER', 'CHORALE', 'CHORTLE', 'CHOWDER', 'CHRONIC',
            'CHUCKLE', 'CHUFFED', 'CHUTNEY', 'CIRCUIT', 'CISTERN', 'CITADEL', 'CITIZEN', 'CIVVIES', 'CLAMBER', 'CLAMOUR', 'CLANGER',
            'CLAPPER', 'CLARIFY', 'CLARION', 'CLARITY', 'CLASPER', 'CLASSIC', 'CLATTER', 'CLEANER', 'CLEANLY', 'CLEANSE', 'CLEANUP',
            'CLEARLY', 'CLEAVER', 'CLEMENT', 'CLIMATE', 'CLIMBER', 'CLINKER', 'CLIPPED', 'CLIQUEY', 'CLOBBER', 'CLONING', 'CLOSELY',
            'CLOSING', 'CLOTHES', 'CLOTURE', 'CLOUDED', 'CLUNKER', 'CLUSTER', 'CLUTTER', 'COARSEN', 'COASTAL', 'COASTER', 'COATING',
            'COBBLED', 'COBBLER', 'COCAINE', 'COCHLEA', 'COCKADE', 'COCKPIT', 'COCONUT', 'CODFISH', 'COEXIST', 'COGENCY', 'COGNATE',
            'COHABIT', 'COINAGE', 'COLICKY', 'COLLAGE', 'COLLATE', 'COLLECT', 'COLLEGE', 'COLLIDE', 'COLLIER', 'COLLUDE', 'COLOGNE',
            'COLONEL', 'COLOURS', 'COLTISH', 'COMBINE', 'COMFORT', 'COMICAL', 'COMMAND', 'COMMEND', 'COMMENT', 'COMMODE', 'COMMONS',
            'COMMUNE', 'COMMUTE', 'COMPACT', 'COMPANY', 'COMPARE', 'COMPASS', 'COMPERE', 'COMPETE', 'COMPILE', 'COMPLEX', 'COMPOSE',
            'COMPOST', 'COMPOTE', 'COMPUTE', 'COMRADE', 'CONCAVE', 'CONCEAL', 'CONCEDE', 'CONCEIT', 'CONCEPT', 'CONCERN', 'CONCERT',
            'CONCISE', 'CONCOCT', 'CONCORD', 'CONCUSS', 'CONDEMN', 'CONDOLE', 'CONDONE', 'CONDUCE', 'CONDUCT', 'CONDUIT', 'CONFESS',
            'CONFIDE', 'CONFINE', 'CONFIRM', 'CONFORM', 'CONFUSE', 'CONFUTE', 'CONGEAL', 'CONICAL', 'CONIFER', 'CONJOIN', 'CONJURE',
            'CONKERS', 'CONNECT', 'CONNIVE', 'CONNOTE', 'CONQUER', 'CONSENT', 'CONSIGN', 'CONSIST', 'CONSOLE', 'CONSORT', 'CONSULT',
            'CONSUME', 'CONTACT', 'CONTAIN', 'CONTEND', 'CONTENT', 'CONTEST', 'CONTEXT', 'CONTORT', 'CONTOUR', 'CONTROL', 'CONTUSE',
            'CONVENE', 'CONVENT', 'CONVERT', 'CONVICT', 'COOKERY', 'COOKING', 'COOLANT', 'COOTIES', 'COPILOT', 'COPIOUS', 'COPPICE',
            'COPYCAT', 'CORDAGE', 'CORDIAL', 'CORKAGE', 'CORNICE', 'CORNROW', 'COROLLA', 'CORONER', 'CORONET', 'CORRECT', 'CORRIDA',
            'CORRODE', 'CORRUPT', 'CORSAGE', 'CORSAIR', 'CORTEGE', 'COSTING', 'COSTUME', 'COTTAGE', 'COUNCIL', 'COUNSEL', 'COUNTER',
            'COUNTRY', 'COUPLET', 'COURAGE', 'COURIER', 'COURTLY', 'COUTURE', 'COVERED', 'COVETED', 'COWBELL', 'COWGIRL', 'COWHAND',
            'COWHERD', 'COWHIDE', 'COWSHED', 'COWSLIP', 'COXCOMB', 'COYNESS', 'CRABBED', 'CRACKED', 'CRACKER', 'CRACKLE', 'CRACKUP',
            'CRAMMER', 'CRAMPED', 'CRAVING', 'CRAWDAD', 'CRAWLER', 'CREAMER', 'CREASED', 'CREATOR', 'CREDITS', 'CREEPER', 'CREMATE',
            'CREVICE', 'CRICKET', 'CRIMSON', 'CRINKLE', 'CRINKLY', 'CRIPPLE', 'CRISPER', 'CRITTER', 'CROCHET', 'CROCKET', 'CROFTER',
            'CROOKED', 'CROPPER', 'CROQUET', 'CROSIER', 'CROUTON', 'CROWBAR', 'CROWDED', 'CROZIER', 'CRUCIAL', 'CRUCIFY', 'CRUDITY',
            'CRUELTY', 'CRUISER', 'CRULLER', 'CRUMBLE', 'CRUMBLY', 'CRUMPET', 'CRUMPLE', 'CRUNCHY', 'CRUSADE', 'CRYBABY', 'CRYPTIC',
            'CRYSTAL', 'CUBICAL', 'CUBICLE', 'CUCKOLD', 'CUISINE', 'CULPRIT', 'CULTURE', 'CULVERT', 'CUMQUAT', 'CUMULUS', 'CUNNING',
            'CURABLE', 'CURATOR', 'CURIOUS', 'CURLING', 'CURRANT', 'CURRENT', 'CURSING', 'CURSIVE', 'CURSORY', 'CURTAIL', 'CURTAIN',
            'CUSHION', 'CUSTARD', 'CUSTODY', 'CUSTOMS', 'CUTAWAY', 'CUTBACK', 'CUTLERY', 'CUTOFFS', 'CUTTING', 'CYCLING', 'CYCLIST',
            'CYCLONE', 'CYCLOPS', 'CYNICAL', 'CYPRESS', 'CZARIST'
        ]
    },
    'D': {
        '3': [
            'DAB', 'DAD', 'DAM', 'DAN', 'DAW', 'DAY', 'DEN', 'DEW', 'DIB', 'DIE', 'DIG', 'DIM', 'DIN', 'DIP', 'DOC', 'DOE', 'DOG', 'DOH',
            'DON', 'DOT', 'DRY', 'DUB', 'DUD', 'DUE', 'DUN', 'DUO', 'DYE'
        ],
        '4': [
            'DAFT', 'DAIS', 'DALE', 'DAME', 'DAMN', 'DAMP', 'DANK', 'DARE', 'DARK', 'DARN', 'DART', 'DASH', 'DATA', 'DATE', 'DAUB', 'DAWN',
            'DAZE', 'DEAD', 'DEAF', 'DEAL', 'DEAN', 'DEAR', 'DEBT', 'DECK', 'DEED', 'DEEM', 'DEEP', 'DEER', 'DEFT', 'DEFY', 'DELI', 'DELL',
            'DEMO', 'DENT', 'DENY', 'DERV', 'DESK', 'DEWY', 'DIAL', 'DIBS', 'DICE', 'DICK', 'DIET', 'DIGS', 'DIKE', 'DILL', 'DIME', 'DINE',
            'DINO', 'DINT', 'DIRE', 'DIRK', 'DIRT', 'DISC', 'DISH', 'DISK', 'DIVA', 'DIVE', 'DOCK', 'DODO', 'DOER', 'DOFF', 'DOGE', 'DOLE',
            'DOLL', 'DOLT', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DOPE', 'DORK', 'DORM', 'DORY', 'DOSE', 'DOSH', 'DOSS', 'DOTE', 'DOTH', 'DOUR',
            'DOVE', 'DOWN', 'DOZE', 'DOZY', 'DRAB', 'DRAG', 'DRAM', 'DRAT', 'DRAW', 'DRAY', 'DRIP', 'DROP', 'DRUB', 'DRUG', 'DRUM', 'DUAL',
            'DUCK', 'DUCT', 'DUDE', 'DUDS', 'DUEL', 'DUES', 'DUET', 'DUFF', 'DUKE', 'DULL', 'DULY', 'DUMB', 'DUMP', 'DUNE', 'DUNG', 'DUNK',
            'DUPE', 'DUSK', 'DUST', 'DUTY', 'DYAD', 'DYER', 'DYKE'
        ],
        '5': [
            'DADDY', 'DAFFY', 'DAILY', 'DAIRY', 'DAISY', 'DALLY', 'DANCE', 'DANDY', 'DARTS', 'DATED', 'DATUM', 'DAUNT', 'DAVIT', 'DAZED',
            'DEATH', 'DEBAR', 'DEBIT', 'DEBUG', 'DEBUT', 'DECAF', 'DECAY', 'DECOR', 'DECOY', 'DECRY', 'DEFER', 'DEFOG', 'DEIFY', 'DEIGN',
            'DEISM', 'DEIST', 'DEITY', 'DELAY', 'DELTA', 'DELVE', 'DEMON', 'DEMUR', 'DENIM', 'DENSE', 'DEPOT', 'DEPTH', 'DERBY', 'DERRY',
            'DETER', 'DETOX', 'DEUCE', 'DEVIL', 'DIARY', 'DICEY', 'DICKY', 'DIDDY', 'DIGIT', 'DILLY', 'DINER', 'DINGO', 'DINGY', 'DINKY',
            'DIPPY', 'DIRGE', 'DIRTY', 'DISCO', 'DITCH', 'DITTO', 'DITTY', 'DIVAN', 'DIVER', 'DIVVY', 'DIXIE', 'DIZZY', 'DODGE', 'DODGY',
            'DOGGO', 'DOGGY', 'DOGIE', 'DOGMA', 'DOILY', 'DOING', 'DOLLY', 'DOMED', 'DONOR', 'DONUT', 'DOPEY', 'DORKY', 'DOTTY', 'DOUBT',
            'DOUGH', 'DOULA', 'DOUSE', 'DOWDY', 'DOWEL', 'DOWER', 'DOWNY', 'DOWRY', 'DOWSE', 'DOZEN', 'DRAFT', 'DRAIN', 'DRAKE', 'DRAMA',
            'DRAPE', 'DRAWL', 'DRAWN', 'DREAD', 'DREAM', 'DREGS', 'DRESS', 'DRIED', 'DRIER', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROID',
            'DROLL', 'DRONE', 'DROOL', 'DROOP', 'DROPS', 'DROSS', 'DROVE', 'DROWN', 'DRUID', 'DRUPE', 'DRYAD', 'DRYER', 'DRYLY', 'DUCAL',
            'DUCAT', 'DUCHY', 'DUCKS', 'DUCKY', 'DUMBO', 'DUMMY', 'DUMPS', 'DUMPY', 'DUNCE', 'DUNNO', 'DURUM', 'DUSKY', 'DUSTY', 'DUVET',
            'DWARF', 'DWELL', 'DYING'
        ],
        '6': [
            'DABBLE', 'DAEMON', 'DACTYL', 'DAGGER', 'DAHLIA', 'DAINTY', 'DAMAGE', 'DAMASK', 'DAMMIT', 'DAMNED', 'DAMPEN', 'DAMPER',
            'DAMSEL', 'DANCER', 'DANDER', 'DANDLE', 'DANGER', 'DANGLE', 'DAPPER', 'DARING', 'DARKEN', 'DASHED', 'DATING', 'DATIVE',
            'DAWDLE', 'DAZZLE', 'DEACON', 'DEADEN', 'DEADLY', 'DEAFEN', 'DEALER', 'DEARLY', 'DEARTH', 'DEBARK', 'DEBASE', 'DEBATE',
            'DEBRIS', 'DEBTOR', 'DEBUNK', 'DECADE', 'DECAMP', 'DECANT', 'DECEIT', 'DECENT', 'DECIDE', 'DECOCT', 'DECODE', 'DECREE',
            'DEDUCE', 'DEDUCT', 'DEEJAY', 'DEEPEN', 'DEEPLY', 'DEFACE', 'DEFAME', 'DEFEAT', 'DEFECT', 'DEFEND', 'DEFILE', 'DEFINE',
            'DEFORM', 'DEFRAY', 'DEFUSE', 'DEGREE', 'DEJECT', 'DELETE', 'DELUDE', 'DELUGE', 'DEMAND', 'DEMEAN', 'DEMENT', 'DEMISE',
            'DEMIST', 'DEMOTE', 'DEMURE', 'DENIAL', 'DENIMS', 'DENOTE', 'DENTAL', 'DENTIN', 'DENUDE', 'DEPART', 'DEPEND', 'DEPICT',
            'DEPLOY', 'DEPORT', 'DEPOSE', 'DEPUTE', 'DEPUTY', 'DERAIL', 'DERIDE', 'DERIVE', 'DERMAL', 'DESCRY', 'DESERT', 'DESIGN',
            'DESIRE', 'DESIST', 'DESPOT', 'DETACH', 'DETAIL', 'DETAIN', 'DETECT', 'DETEST', 'DETOUR', 'DEUCED', 'DEVICE', 'DEVISE',
            'DEVOID', 'DEVOTE', 'DEVOUR', 'DEVOUT', 'DEWLAP', 'DIADEM', 'DIAPER', 'DIBBLE', 'DICKER', 'DICTUM', 'DIDDLE', 'DIESEL',
            'DIETER', 'DIFFER', 'DIGEST', 'DIGGER', 'DIKTAT', 'DILATE', 'DILUTE', 'DIMMER', 'DIMPLE', 'DIMWIT', 'DINGHY', 'DINGLE',
            'DINING', 'DINNER', 'DIPOLE', 'DIPPER', 'DIRECT', 'DISARM', 'DISBAR', 'DISCUS', 'DISHED', 'DISMAL', 'DISMAY', 'DISOWN',
            'DISPEL', 'DISUSE', 'DITHER', 'DIVERS', 'DIVERT', 'DIVEST', 'DIVIDE', 'DIVINE', 'DIVING', 'DOABLE', 'DOBBIN', 'DOCENT',
            'DOCILE', 'DOCKER', 'DOCKET', 'DOCTOR', 'DODDER', 'DODDLE', 'DODGER', 'DOGGED', 'DOGLEG', 'DOINGS', 'DOLLAR', 'DOLLOP',
            'DOLMEN', 'DOLOUR', 'DOMAIN', 'DOMINO', 'DONATE', 'DONKEY', 'DOODAH', 'DOODLE', 'DORMER', 'DORSAL', 'DOSAGE', 'DOSSER',
            'DOTAGE', 'DOTTED', 'DOUBLE', 'DOUBLY', 'DOUCHE', 'DOUGHY', 'DOWNER', 'DRAGGY', 'DRAGON', 'DRAINS', 'DRAPER', 'DRAPES',
            'DRAWER', 'DREAMY', 'DREARY', 'DREDGE', 'DRENCH', 'DRESSY', 'DRIVEL', 'DRIVEN', 'DRIVER', 'DROGUE', 'DROOPY', 'DROPSY',
            'DROVER', 'DROVES', 'DROWSE', 'DROWSY', 'DRUDGE', 'DRYING', 'DUBBED', 'DUBBIN', 'DUENNA', 'DUFFEL', 'DUFFER', 'DUGOUT',
            'DULCET', 'DUMPER', 'DUPERY', 'DUPLEX', 'DURESS', 'DURING', 'DUSTER', 'DYNAMO'
        ],
        '7': [
            'DABBLER', 'DAYTIME', 'DAMNIFY', 'DAPPLED', 'DARESAY', 'DARLING', 'DARNING', 'DASHING', 'DATABLE', 'DAYBOOK', 'DAYTIME',
            'DAZEDLY', 'DEADPAN', 'DEALING', 'DEANERY', 'DEATHLY', 'DEBACLE', 'DEBAUCH', 'DEBRIEF', 'DECEASE', 'DECEIVE', 'DECENCY',
            'DECIBEL', 'DECIDED', 'DECIDER', 'DECIMAL', 'DECLAIM', 'DECLARE', 'DECLINE', 'DECODER', 'DECORUM', 'DECRYPT', 'DEFAULT',
            'DEFENCE', 'DEFENSE', 'DEFIANT', 'DEFICIT', 'DEFLATE', 'DEFLECT', 'DEFRAUD', 'DEFROCK', 'DEFROST', 'DEFUNCT', 'DEGRADE',
            'DELIGHT', 'DELIMIT', 'DELIVER', 'DELOUSE', 'DELTOID', 'DEMERIT', 'DEMESNE', 'DEMIGOD', 'DEMONIC', 'DEMOTIC', 'DENIZEN',
            'DENSITY', 'DENTATE', 'DENTIST', 'DENTURE', 'DEPLANE', 'DEPLETE', 'DEPLORE', 'DEPOSAL', 'DEPOSIT', 'DEPRAVE', 'DEPRESS',
            'DEPRIVE', 'DERANGE', 'DERRICK', 'DERVISH', 'DESCALE', 'DESCANT', 'DESCEND', 'DESCENT', 'DESERTS', 'DESERVE', 'DESKTOP',
            'DESPAIR', 'DESPISE', 'DESPITE', 'DESPOIL', 'DESSERT', 'DESTINE', 'DESTINY', 'DESTROY', 'DETRACT', 'DEVALUE', 'DEVELOP',
            'DEVIANT', 'DEVIATE', 'DEVIOUS', 'DEVISOR', 'DEVOICE', 'DEVOLVE', 'DEVOTED', 'DEWDROP', 'DEWFALL', 'DIAGRAM', 'DIALECT',
            'DIAMOND', 'DIARIST', 'DICKENS', 'DICTATE', 'DICTION', 'DIDDUMS', 'DIETARY', 'DIFFUSE', 'DIGITAL', 'DIGNIFY', 'DIGNITY',
            'DIGRAPH', 'DIGRESS', 'DILEMMA', 'DILUENT', 'DINETTE', 'DINGBAT', 'DIOCESE', 'DIOPTRE', 'DIOXIDE', 'DIPLOMA', 'DIPTYCH',
            'DIREFUL', 'DISABLE', 'DISAVOW', 'DISBAND', 'DISCARD', 'DISCERN', 'DISCMAN', 'DISCORD', 'DISCUSS', 'DISDAIN', 'DISEASE',
            'DISGUST', 'DISHPAN', 'DISHRAG', 'DISJOIN', 'DISLIKE', 'DISMISS', 'DISOBEY', 'DISPLAY', 'DISPORT', 'DISPOSE', 'DISPUTE',
            'DISROBE', 'DISRUPT', 'DISSECT', 'DISSENT', 'DISTAFF', 'DISTANT', 'DISTEND', 'DISTICH', 'DISTILL', 'DISTORT', 'DISTURB',
            'DISUSED', 'DIURNAL', 'DIVERGE', 'DIVERSE', 'DIVIDED', 'DIVIDER', 'DIVINER', 'DIVISOR', 'DIVORCE', 'DIVULGE', 'DOCKAGE',
            'DOCKING', 'DOESKIN', 'DOGFISH', 'DOGGISH', 'DOGSLED', 'DOGTROT', 'DOGWOOD', 'DOLEFUL', 'DOLPHIN', 'DOLTISH', 'DOORMAN',
            'DOORMAT', 'DOORWAY', 'DORMANT', 'DOSSIER', 'DOUBLES', 'DOUBLET', 'DOUGHTY', 'DOWAGER', 'DRAFTEE', 'DRAGGLE', 'DRAGNET',
            'DRAGOON', 'DRAPERY', 'DRASTIC', 'DRAUGHT', 'DRAWERS', 'DRAWING', 'DREAMER', 'DREDGER', 'DRESSER', 'DRIBBLE', 'DRIBLET',
            'DRIFTER', 'DRIVING', 'DRIZZLE', 'DROPOUT', 'DROPPER', 'DROUGHT', 'DRUMMER', 'DRUNKEN', 'DUALISM', 'DUALITY', 'DUBBING',
            'DUBIETY', 'DUBIOUS', 'DUCHESS', 'DUCTILE', 'DUDGEON', 'DUELLER', 'DUKEDOM', 'DULCIFY', 'DULLARD', 'DUMPING', 'DUNGEON',
            'DUNKING', 'DURABLE', 'DUSTBIN', 'DUSTING', 'DUSTMAN', 'DUTEOUS', 'DUTIFUL', 'DWINDLE', 'DYEABLE', 'DYNAMIC', 'DYNASTY'
        ]
    },
    'E': {
        '3': [
            'EAR', 'EAT', 'EBB', 'EEL', 'EFF', 'EFT', 'EGG', 'EGO', 'EKE', 'ELF', 'ELK', 'ELL', 'ELM', 'EMU', 'END', 'ERA', 'ERE', 'ERG',
            'ERN', 'ERR', 'EVE', 'EWE', 'EYE'
        ],
        '4': [
            'EACH', 'EARL', 'EARN', 'EASE', 'EAST', 'EASY', 'EATS', 'ECHO', 'ECRU', 'EDDY', 'EDGE', 'EDGY', 'EDIT', 'ELAN', 'ELSE', 'EMIR',
            'EMIT', 'ENVY', 'EPEE', 'EPIC', 'ERGO', 'ESPY', 'ETCH', 'EVEN', 'EVER', 'EVIL', 'EWER', 'EXAM', 'EXIT'
        ],
        '5': [
            'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EASEL', 'EATER', 'EAVES', 'EBONY', 'EDICT', 'EDIFY', 'EERIE', 'EGRET', 'EIGHT',
            'EJECT', 'ELAND', 'ELATE', 'ELBOW', 'ELDER', 'ELECT', 'ELEGY', 'ELIDE', 'ELITE', 'ELOPE', 'ELUDE', 'ELVEN', 'EMAIL',
            'EMBED', 'EMBER', 'EMEND', 'EMERY', 'EMPTY', 'ENACT', 'ENDOW', 'ENDUE', 'ENEMA', 'ENEMY', 'ENJOY', 'ENNUI', 'ENROL',
            'ENSUE', 'ENTER', 'ENTRY', 'ENVOY', 'EPOCH', 'EQUAL', 'EQUIP', 'ERASE', 'ERECT', 'ERGOT', 'ERODE', 'ERROR', 'ERUCT',
            'ERUPT', 'ESSAY', 'ETHER', 'ETHIC', 'ETHOS', 'ETHYL', 'EVADE', 'EVENS', 'EVENT', 'EVERT', 'EVERY', 'EVICT', 'EVOKE',
            'EXACT', 'EXALT', 'EXCEL', 'EXERT', 'EXILE', 'EXIST', 'EXPAT', 'EXPEL', 'EXTOL', 'EXTRA', 'EXUDE', 'EXULT', 'EYRIE'
        ],
        '6': [
            'EAGLET', 'EARFUL', 'EARTHY', 'EARWAX', 'EARWIG', 'EASILY', 'EATERY', 'EATING', 'ECHOIC', 'ECLAIR', 'ECZEMA', 'EDGING',
            'EDIBLE', 'EDITOR', 'EFFACE', 'EFFECT', 'EFFETE', 'EFFIGY', 'EFFORT', 'EFFUSE', 'EGOISM', 'EGOIST', 'EGRESS', 'EIGHTH',
            'EIGHTY', 'EITHER', 'ELAPSE', 'ELATED', 'ELDEST', 'ELEVEN', 'ELFISH', 'ELICIT', 'ELIXIR', 'EMBALM', 'EMBANK', 'EMBARK',
            'EMBERS', 'EMBLEM', 'EMBODY', 'EMBOSS', 'EMBRYO', 'EMERGE', 'EMETIC', 'EMPIRE', 'EMPLOY', 'ENABLE', 'ENAMEL', 'ENCAMP',
            'ENCASE', 'ENCODE', 'ENCORE', 'ENDEAR', 'ENDING', 'ENDIVE', 'ENDURE', 'ENERGY', 'ENFOLD', 'ENGAGE', 'ENGINE', 'ENGULF',
            'ENIGMA', 'ENJOIN', 'ENLIST', 'ENMESH', 'ENMITY', 'ENOUGH', 'ENRAGE', 'ENRICH', 'ENROLL', 'ENSIGN', 'ENSURE', 'ENTAIL',
            'ERASER', 'ESCAPE', 'ENTICE', 'ENTIRE', 'ENTITY', 'ENTOMB', 'ENTRAP', 'ENWRAP', 'ENZYME', 'EPONYM', 'EQUATE', 'EQUINE',
            'EQUITY', 'ERASER', 'ERMINE', 'EROTIC', 'ERRAND', 'ERRANT', 'ERRATA', 'ERSATZ', 'ESCAPE', 'ESCHEW', 'ESCORT', 'ESCROW',
            'ESPRIT', 'ESTATE', 'ESTEEM', 'ETHICS', 'ETHNIC', 'EULOGY', 'EUNUCH', 'EUREKA', 'EVINCE', 'EVOLVE', 'EXCEED', 'EXCEPT',
            'EXCESS', 'EXCISE', 'EXCITE', 'EXCUSE', 'EXEMPT', 'EXEUNT', 'EXHALE', 'EXHORT', 'EXHUME', 'EXODUS', 'EXOTIC', 'EXPAND',
            'EXPECT', 'EXPEND', 'EXPERT', 'EXPIRE', 'EXPIRY', 'EXPORT', 'EXPOSE', 'EXTANT', 'EXTEND', 'EXTENT', 'EXTORT', 'EYEFUL',
            'EYELET', 'EYELID'
        ],
        '7': [
            'EARLDOM', 'EARLOBE', 'EARMARK', 'EARNEST', 'EARPLUG', 'EARRING', 'EARSHOT', 'EARTHEN', 'EARTHLY', 'EASTERN', 'EATABLE',
            'ECLIPSE', 'ECLOGUE', 'ECOLOGY', 'ECONOMY', 'ECSTASY', 'ECTOPIC', 'EDIBLES', 'EDIFICE', 'EDITING', 'EDITION', 'EDUCATE',
            'EFFABLE', 'EFFECTS', 'EGOTISM', 'EGOTIST', 'EJECTOR', 'ELASTIC', 'ELATION', 'ELDERLY', 'ELECTOR', 'ELEGANT', 'ELEGIAC',
            'ELEMENT', 'ELEVATE', 'ELISION', 'ELITIST', 'ELLIPSE', 'ELUSIVE', 'EMANATE', 'EMBARGO', 'EMBASSY', 'EMBOLIC', 'EMBOSOM',
            'EMBRACE', 'EMBROIL', 'EMERALD', 'EMINENT', 'EMIRATE', 'EMOTION', 'EMOTIVE', 'EMPATHY', 'EMPEROR', 'EMPIRIC', 'EMPLACE',
            'EMPOWER', 'EMPRESS', 'EMPTIES', 'EMULATE', 'ENAMOUR', 'ENCHAIN', 'ENCHANT', 'ENCLAVE', 'ENCLOSE', 'ENCRUST', 'ENDEMIC',
            'ENDGAME', 'ENDLESS', 'ENDORSE', 'ENDWAYS', 'ENFORCE', 'ENGAGED', 'ENGORGE', 'ENGRAVE', 'ENGROSS', 'ENHANCE', 'ENLARGE',
            'ENLIVEN', 'ENNOBLE', 'ENPLANE', 'ENQUIRE', 'ENQUIRY', 'ENSLAVE', 'ENSNARE', 'ENTENTE', 'ENTERIC', 'ENTHRAL', 'ENTITLE',
            'ENTRAIN', 'ENTRANT', 'ENTREAT', 'ENTROPY', 'ENTRUST', 'ENTWINE', 'ENVELOP', 'ENVENOM', 'ENVIOUS', 'ENVIRON', 'EPICURE',
            'EPIGRAM', 'EPISODE', 'EPITAPH', 'EPITHET', 'EPITOME', 'EPSILON', 'EQUABLE', 'EQUATOR', 'EQUERRY', 'EQUINOX', 'ERASURE',
            'EROSION', 'EROSIVE', 'EROTICA', 'ERRATIC', 'ERUDITE', 'ESPOUSE', 'ESQUIRE', 'ESSENCE', 'ESTHETE', 'ESTUARY', 'ETCHING',
            'ETERNAL', 'ETHANOL', 'ETHICAL', 'EUPHONY', 'EVASION', 'EVASIVE', 'EVENING', 'EVIDENT', 'EXACTLY', 'EXAMINE', 'EXAMPLE',
            'EXCITED', 'EXCLAIM', 'EXCLUDE', 'EXCRETE', 'EXECUTE', 'EXHAUST', 'EXHIBIT', 'EXIGENT', 'EXOTICA', 'EXPANSE', 'EXPENSE',
            'EXPIATE', 'EXPLAIN', 'EXPLODE', 'EXPLOIT', 'EXPLORE', 'EXPOSED', 'EXPOUND', 'EXPRESS', 'EXPUNGE', 'EXTINCT', 'EXTRACT',
            'EXTREME', 'EXTRUDE', 'EXURBAN', 'EYEBALL', 'EYEBROW', 'EYELASH', 'EYELESS', 'EYESHOT', 'EYESORE', 'EYEWASH'
        ]
    },
    'F': {
        '3': [
            'FAD', 'FAG', 'FAN', 'FAR', 'FAT', 'FAX', 'FEE', 'FEN', 'FEW', 'FEY', 'FEZ', 'FIE', 'FIG', 'FIN', 'FIR', 'FIT', 'FIX', 'FOB',
            'FOE', 'FOG', 'FOO', 'FOP', 'FOR', 'FOX', 'FRO', 'FRY', 'FUG', 'FUN', 'FUR'
        ],
        '4': [
            'FACE', 'FACT', 'FADE', 'FAIL', 'FAIN', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FANG', 'FARE', 'FARM', 'FART', 'FAST', 'FATE', 'FAUN',
            'FAWN', 'FEAR', 'FEAT', 'FEED', 'FEEL', 'FELL', 'FELT', 'FEND', 'FERN', 'FETE', 'FEUD', 'FIAT', 'FIEF', 'FIFE', 'FILE', 'FILL',
            'FILM', 'FIND', 'FINE', 'FINK', 'FIRE', 'FIRM', 'FISH', 'FIST', 'FIVE', 'FIZZ', 'FLAB', 'FLAG', 'FLAM', 'FLAN', 'FLAP', 'FLAT',
            'FLAW', 'FLAX', 'FLAY', 'FLEA', 'FLEE', 'FLEX', 'FLIP', 'FLIT', 'FLOE', 'FLOG', 'FLOP', 'FLOW', 'FLUB', 'FLUE', 'FLUX', 'FOAL',
            'FOAM', 'FOIL', 'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD', 'FORE', 'FORK', 'FORM', 'FORT', 'FOSS', 'FOUL',
            'FOUR', 'FRET', 'FROG', 'FOWL', 'FOXY', 'FRAY', 'FREE', 'FRET', 'FRIT', 'FROG', 'FROM', 'FUEL', 'FULL', 'FUME', 'FUND', 'FUNK',
            'FURL', 'FURY', 'FUSE', 'FUSS', 'FUZZ'
        ],
        '5': [
            'FABLE', 'FACET', 'FADDY', 'FADED', 'FAINT', 'FAIRY', 'FAITH', 'FAKER', 'FAKIR', 'FALLS', 'FALSE', 'FAMED', 'FANCY', 'FANNY',
            'FARAD', 'FARCE', 'FATAL', 'FATED', 'FATTY', 'FAULT', 'FAUNA', 'FAVOR', 'FEAST', 'FECES', 'FEIGN', 'FEINT', 'FELON', 'FEMUR',
            'FENCE', 'FERRY', 'FETAL', 'FETCH', 'FETID', 'FETUS', 'FEVER', 'FIBRE', 'FICUS', 'FIELD', 'FIEND', 'FIERY', 'FIFTH', 'FIFTY',
            'FIGHT', 'FILCH', 'FILET', 'FILLY', 'FILMY', 'FILTH', 'FINAL', 'FINCH', 'FINNY', 'FJORD', 'FIRST', 'FIRTH', 'FISHY', 'FITCH',
            'FIVER', 'FIXED', 'FIXER', 'FIZZY', 'FLAIL', 'FLAIR', 'FLAKE', 'FLAKY', 'FLAME', 'FLANK', 'FLARE', 'FLASH', 'FLASK', 'FLECK',
            'FLEET', 'FLESH', 'FLICK', 'FLIER', 'FLIES', 'FLING', 'FLINT', 'FLIRT', 'FLOAT', 'FLOCK', 'FLOOD', 'FLOOR', 'FLORA', 'FLOSS',
            'FLOUR', 'FLOUT', 'FLUFF', 'FLUID', 'FLUKE', 'FLUKY', 'FLUME', 'FLUNK', 'FLUSH', 'FLUTE', 'FOAMY', 'FOCAL', 'FOCUS', 'FOGGY',
            'FOIST', 'FOLIO', 'FOLKS', 'FORAY', 'FORCE', 'FORGE', 'FORGO', 'FORTE', 'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FOUNT', 'FOYER',
            'FRAIL', 'FRAME', 'FRANC', 'FRANK', 'FRAUD', 'FREAK', 'FREON', 'FRESH', 'FRIAR', 'FRIED', 'FRIES', 'FRILL', 'FRISK', 'FRIZZ',
            'FROCK', 'FROND', 'FRONT', 'FROST', 'FROTH', 'FROWN', 'FRUIT', 'FOUND', 'FUNNY', 'FRUMP', 'FRYER', 'FUDGE', 'FUGAL', 'FUGGY',
            'FUGUE', 'FULLY', 'FUMES', 'FUNDS', 'FUNKY', 'FUNNY', 'FURRY', 'FURZE', 'FUSSY', 'FUSTY', 'FUZZY'
        ],
        '6': [
            'FABLED', 'FABRIC', 'FACADE', 'FACIAL', 'FACILE', 'FACING', 'FACTOR', 'FAGGED', 'FAGGOT', 'FAIRLY', 'FALCON', 'FALLEN',
            'FALLOW', 'FALTER', 'FAMILY', 'FAMINE', 'FAMOUS', 'FARMER', 'FARROW', 'FASCIA', 'FASTEN', 'FATHER', 'FATHOM', 'FATTEN',
            'FAUCET', 'FAULTY', 'FAVOUR', 'FEALTY', 'FECUND', 'FEDORA', 'FEEBLE', 'FEEDER', 'FEELER', 'FELINE', 'FELLOW', 'FELONY',
            'FEMALE', 'FENCER', 'FENDER', 'FENNEL', 'FERRET', 'FERULE', 'FESTAL', 'FESTER', 'FETISH', 'FETTER', 'FETTLE', 'FEUDAL',
            'FIANCE', 'FIASCO', 'FIBULA', 'FICKLE', 'FIDDLE', 'FIDDLY', 'FIDGET', 'FIERCE', 'FIESTA', 'FIGURE', 'FILIAL', 'FILLER',
            'FILLET', 'FILLIP', 'FILTER', 'FILTHY', 'FINALE', 'FINALS', 'FINDER', 'FINERY', 'FINGER', 'FINISH', 'FINITE', 'FIRING',
            'FIRKIN', 'FISCAL', 'FISHER', 'FITFUL', 'FITTED', 'FITTER', 'FIXITY', 'FIZZLE', 'FLABBY', 'FLAGON', 'FLAMBE', 'FLANGE',
            'FLINCH', 'FLAPPY', 'FLARED', 'FLARES', 'FLASHY', 'FLATLY', 'FLAUNT', 'FLAVOR', 'FLAXEN', 'FLEECE', 'FLEECY', 'FLESHY',
            'FLIGHT', 'FLIMSY', 'FLINCH', 'FLINTY', 'FLOATS', 'FLOPPY', 'FLORAL', 'FLORID', 'FLOURY', 'FLOWER', 'FLUENT', 'FLUFFY',
            'FLUNKY', 'FLURRY', 'FLYING', 'FODDER', 'FOETAL', 'FOETUS', 'FOIBLE', 'FOLDER', 'FOLIUM', 'FOLKSY', 'FOLLOW', 'FOMENT',
            'FONDLE', 'FONDLY', 'FONDUE', 'FOOTER', 'FORAGE', 'FORBID', 'FORCED', 'FORCES', 'FOREGO', 'FOREST', 'FORGER', 'FORGET',
            'FORKED', 'FORMAL', 'FORMAT', 'FORMER', 'FOSSIL', 'FOSTER', 'FOURTH', 'FOWLER', 'FRACAS', 'FRAPPE', 'FREAKY', 'FREELY',
            'FREEZE', 'FREEZY', 'FRENZY', 'FRESCO', 'FRIARY', 'FRIDAY', 'FRIDGE', 'FRIEND', 'FRIEZE', 'FRIGHT', 'FRIGID', 'FRILLS',
            'FRINGE', 'FRISKY', 'FRIZZY', 'FROLIC', 'FROSTY', 'FROTHY', 'FROZEN', 'FRUGAL', 'FRUITY', 'FUDDLE', 'FULFIL', 'FULLER',
            'FUMBLE', 'FUNGUS', 'FUNNEL', 'FURORE', 'FURRED', 'FURROW', 'FUSION', 'FUTILE', 'FUTURE'
        ],
        '7': [
            'FACINGS', 'FACTION', 'FACTOID', 'FACTORY', 'FACTUAL', 'FACULTY', 'FADDISH', 'FAILING', 'FAILURE', 'FAIRING', 'FAIRWAY',
            'FAJITAS', 'FALAFEL', 'FALLACY', 'FALLOUT', 'FALSIES', 'FALSIFY', 'FALSITY', 'FANATIC', 'FANFARE', 'FANTAIL', 'FANTASY',
            'FANZINE', 'FARAWAY', 'FARMING', 'FARRAGO', 'FARRIER', 'FARTHER', 'FASCIST', 'FASHION', 'FATEFUL', 'FATHEAD', 'FATIGUE',
            'FATUITY', 'FATUOUS', 'FEARFUL', 'FEATHER', 'FEATURE', 'FEBRILE', 'FEDERAL', 'FEEDING', 'FEELING', 'FEMORAL', 'FENCING',
            'FERMENT', 'FERRULE', 'FERTILE', 'FERVENT', 'FERVOUR', 'FESTIVE', 'FESTOON', 'FETLOCK', 'FEVERED', 'FIANCEE', 'FIBROUS',
            'FICTION', 'FIDDLER', 'FIDGETS', 'FIDGETY', 'FIEFDOM', 'FIELDER', 'FIFTEEN', 'FIGHTER', 'FIGMENT', 'FILBERT', 'FILINGS',
            'FILLING', 'FINALLY', 'FINANCE', 'FINDING', 'FINESSE', 'FINICKY', 'FIREARM', 'FIREBOX', 'FIREBUG', 'FIREFLY', 'FIREMAN',
            'FIRSTLY', 'FISHERY', 'FISHING', 'FISHNET', 'FISSILE', 'FISSION', 'FISSURE', 'FISTFUL', 'FISTULA', 'FITMENT', 'FITNESS',
            'FITTING', 'FIXATED', 'FIXEDLY', 'FIXTURE', 'FLACCID', 'FLAGMAN', 'FLAMING', 'FLANNEL', 'FLAPPER', 'FLASHER', 'FLATLET',
            'FLATTEN', 'FLATTER', 'FLATTOP', 'FLAVOUR', 'FLEABAG', 'FLEAPIT', 'FLESHLY', 'FLEXION', 'FLICKER', 'FLIGHTY', 'FLIPPER',
            'FLOATER', 'FLORIST', 'FLOTSAM', 'FLOUNCE', 'FLOWERY', 'FLUENCY', 'FLUMMOX', 'FLUNKEY', 'FLUSTER', 'FLUTING', 'FLUTIST',
            'FLUTTER', 'FLUVIAL', 'FLYAWAY', 'FLYLEAF', 'FLYOVER', 'FLYTRAP', 'FOGHORN', 'FOLDING', 'FOLIAGE', 'FONDANT', 'FOOLERY',
            'FOOLISH', 'FOOTAGE', 'FOOTING', 'FOOTMAN', 'FOOTSIE', 'FOOTWAY', 'FOPPISH', 'FORBEAR', 'FORCEPS', 'FOREARM', 'FOREIGN',
            'FORELEG', 'FOREMAN', 'FORESEE', 'FOREVER', 'FORFEIT', 'FORGERY', 'FORGIVE', 'FORKFUL', 'FORLORN', 'FORMANT', 'FORMULA',
            'FORSAKE', 'FORTIES', 'FORTIFY', 'FORTUNE', 'FORWARD', 'FOUNDER', 'FOUNDRY', 'FOXHOLE', 'FOXTROT', 'FRACTAL', 'FRAGILE',
            'FRAILTY', 'FRANKLY', 'FRANTIC', 'FRAUGHT', 'FRAZZLE', 'FRECKLE', 'FREEBIE', 'FREEDOM', 'FREEMAN', 'FREESIA', 'FREEWAY',
            'FREEZER', 'FREIGHT', 'FRESHEN', 'FRESHER', 'FRESHET', 'FRESHLY', 'FRETFUL', 'FRETSAW', 'FRIABLE', 'FRIBBLE', 'FRIGATE',
            'FRISSON', 'FRITTER', 'FRIZZLE', 'FRONTAL', 'FRUSTUM', 'FUCHSIA', 'FULCRUM', 'FULFILL', 'FULSOME', 'FUNDING', 'FUNERAL',
            'FUNGOID', 'FUNGOUS', 'FUNNIES', 'FUNNILY', 'FURBISH', 'FURIOUS', 'FURLONG', 'FURNACE', 'FURNISH', 'FURRIER', 'FURTHER',
            'FURTIVE', 'FUSIBLE', 'FUSSPOT'
        ]
    },
    'G': {
        '3': [
            'GAB', 'GAD', 'GAG', 'GAP', 'GAS', 'GAY', 'GEE', 'GEL', 'GEM', 'GEN', 'GET', 'GIG', 'GIN', 'GIT', 'GNU', 'GOB', 'GOD', 'GOO',
            'GOY', 'GUM', 'GUN', 'GUT', 'GUY', 'GYM', 'GYP'
        ],
        '4': [
            'GAFF', 'GAGA', 'GAGE', 'GAIN', 'GAIT', 'GALA', 'GALE', 'GALL', 'GAME', 'GANG', 'GAOL', 'GAPE', 'GARB', 'GASH', 'GASP', 'GATE',
            'GAWK', 'GAWP', 'GAZE', 'GEAR', 'GEEK', 'GELD', 'GENE', 'GENT', 'GERM', 'GHEE', 'GIBE', 'GIFT', 'GILD', 'GILL', 'GILT', 'GIRD',
            'GIRL', 'GIRO', 'GIST', 'GIVE', 'GLAD', 'GLEE', 'GLEN', 'GLIB', 'GLOP', 'GLOW', 'GLUE', 'GLUM', 'GLUT', 'GNAT', 'GNAW', 'GOAD',
            'GOAL', 'GOAT', 'GODS', 'GOER', 'GOLD', 'GOLF', 'GONE', 'GOOD', 'GOOF', 'GOON', 'GORE', 'GORY', 'GOSH', 'GOTH', 'GOUT', 'GOWN',
            'GRAB', 'GRAD', 'GRAM', 'GRAN', 'GRAY', 'GREY', 'GRID', 'GRIM', 'GRIN', 'GRIP', 'GRIT', 'GROG', 'GROW', 'GRUB', 'GUFF', 'GULF',
            'GULL', 'GULP', 'GUNK', 'GURU', 'GUSH', 'GUST', 'GUTS', 'GYRO'
        ],
        '5': [
            'GABLE', 'GAFFE', 'GAILY', 'GAINS', 'GAMER', 'GAMES', 'GAMMA', 'GAMMY', 'GAMUT', 'GARTH', 'GASSY', 'GAUDY', 'GAUGE', 'GAUNT',
            'GAUZE', 'GAUZY', 'GAVEL', 'GAWKY', 'GECKO', 'GENIE', 'GENRE', 'GENTS', 'GENUS', 'GETUP', 'GHOST', 'GHOUL', 'GIANT', 'GIDDY',
            'GIRLY', 'GIRTH', 'GIZMO', 'GIVEN', 'GIVER', 'GLADE', 'GLAND', 'GLANS', 'GLARE', 'GLASS', 'GLAZE', 'GLEAM', 'GLEAN', 'GLIDE',
            'GLINT', 'GLITZ', 'GLOAT', 'GLOBE', 'GLOOM', 'GLORY', 'GLOSS', 'GLOVE', 'GLUEY', 'GLUON', 'GNASH', 'GNOME', 'GODLY', 'GOFER',
            'GOING', 'GOLLY', 'GONAD', 'GONER', 'GONZO', 'GOODS', 'GOODY', 'GOOEY', 'GOOFY', 'GOOSE', 'GORGE', 'GORSE', 'GOUGE', 'GOURD',
            'GOUTY', 'GRABS', 'GRACE', 'GRADE', 'GRAFT', 'GRAIL', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS', 'GRATE',
            'GRAVE', 'GRAVY', 'GRAZE', 'GREAT', 'GREBE', 'GREED', 'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIME', 'GRIMY', 'GRIND', 'GRIPE',
            'GRIST', 'GRITS', 'GROAN', 'GROAT', 'GROIN', 'GROOM', 'GROPE', 'GROSS', 'GROUP', 'GROUT', 'GROVE', 'GROWL', 'GROWN', 'GRUEL',
            'GRUFF', 'GRUNT', 'GUANO', 'GUARD', 'GUAVA', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILE', 'GUILT', 'GUISE', 'GULAG', 'GULCH',
            'GULLY', 'GUMMY', 'GUNGE', 'GUNGY', 'GUNKY', 'GUSTO', 'GUSTY', 'GUTSY', 'GYPSY'
        ],
        '6': [
            'GABBLE', 'GABLED', 'GADFLY', 'GADGET', 'GAFFER', 'GAGGLE', 'GAIETY', 'GAINER', 'GAITER', 'GALAXY', 'GALLEY', 'GALLON',
            'GALLOP', 'GALORE', 'GAMBIT', 'GAMBLE', 'GAMBOL', 'GAMELY', 'GAMING', 'GAMMON', 'GANDER', 'GANNET', 'GANTRY', 'GAOLER',
            'GAPING', 'GARAGE', 'GARBLE', 'GARDEN', 'GARGLE', 'GARISH', 'GARLIC', 'GARNER', 'GARTER', 'GASKET', 'GATEAU', 'GATHER',
            'GAUCHE', 'GAZEBO', 'GEISHA', 'GENDER', 'GENIAL', 'GENIUS', 'GENOME', 'GENTLE', 'GENTLY', 'GENTRY', 'GERBIL', 'GERUND',
            'GEWGAW', 'GEYSER', 'GHETTO', 'GIBBER', 'GIBBET', 'GIBBON', 'GIFTED', 'GIGGLE', 'GIGOLO', 'GILDER', 'GIMLET', 'GINGER',
            'GIRDER', 'GIRDLE', 'GIRLIE', 'GLADLY', 'GLANCE', 'GLASSY', 'GLIDER', 'GLITCH', 'GLITZY', 'GLOBAL', 'GLOOMY', 'GLOSSY',
            'GLOVES', 'GOTHIC', 'GRANNY', 'GLOVER', 'GLOWER', 'GLUTEN', 'GNARLY', 'GOATEE', 'GOBBET', 'GOBBLE', 'GOBLET', 'GOBLIN',
            'GODSON', 'GOGGLE', 'GOITRE', 'GOLDEN', 'GOLFER', 'GOODLY', 'GOPHER', 'GOSPEL', 'GOSSIP', 'GOTCHA', 'GOTHIC', 'GOVERN',
            'GRADER', 'GRAINY', 'GRANGE', 'GRANNY', 'GRASSY', 'GRATER', 'GRATIS', 'GRAVEL', 'GRAVEN', 'GREASE', 'GREASY', 'GREEDY',
            'GREENS', 'GRIEVE', 'GRIMLY', 'GRIPES', 'GRIPPE', 'GRISLY', 'GRITTY', 'GROATS', 'GROCER', 'GROGGY', 'GROOVE', 'GROOVY',
            'GROPER', 'GROTTO', 'GROTTY', 'GROUCH', 'GROUND', 'GROUSE', 'GROVEL', 'GROWER', 'GROWTH', 'GRUBBY', 'GRUDGE', 'GRUMPY',
            'GRUNGY', 'GUFFAW', 'GUIDED', 'GUILTY', 'GUINEA', 'GUITAR', 'GULDEN', 'GULLET', 'GUNMAN', 'GUNNER', 'GURGLE', 'GUSHER',
            'GUTTER', 'GUZZLE', 'GYPSUM', 'GYRATE'
        ],
        '7': [
            'GAINFUL', 'GAINSAY', 'GALLANT', 'GALLEON', 'GALLERY', 'GALLING', 'GALLOWS', 'GALUMPH', 'GAMBLER', 'GANGWAY', 'GARBAGE',
            'GARLAND', 'GARMENT', 'GARNISH', 'GASEOUS', 'GASPING', 'GASTRIC', 'GATEWAY', 'GAUDILY', 'GAYNESS', 'GAZELLE', 'GAZETTE',
            'GELDING', 'GENERAL', 'GENERIC', 'GENESIS', 'GENETIC', 'GENITAL', 'GENTEEL', 'GENUINE', 'GEODESY', 'GEOLOGY', 'GERMANE',
            'GESTALT', 'GESTURE', 'GETAWAY', 'GHASTLY', 'GHERKIN', 'GHOSTLY', 'GIBBOUS', 'GIBLETS', 'GIGABIT', 'GILLION', 'GIMMICK',
            'GINSENG', 'GIRAFFE', 'GIRLISH', 'GIZZARD', 'GLACIAL', 'GLACIER', 'GLADDEN', 'GLAMOUR', 'GLARING', 'GLASSES', 'GLAZIER',
            'GLAZING', 'GLEEFUL', 'GLIDING', 'GLIMMER', 'GLIMPSE', 'GLISTEN', 'GLISTER', 'GLITTER', 'GLOBULE', 'GLORIFY', 'GLOTTAL',
            'GLOTTIS', 'GLOWING', 'GLUCOSE', 'GLUTTON', 'GNARLED', 'GNAWING', 'GODDAMN', 'GODDESS', 'GODHEAD', 'GODLESS', 'GODLIKE',
            'GODSEND', 'GOGGLES', 'GOLFING', 'GOLIATH', 'GONDOLA', 'GOODBYE', 'GOODISH', 'GORILLA', 'GOSLING', 'GOSSIPY', 'GOULASH',
            'GOURMET', 'GRADING', 'GRADUAL', 'GRAFTER', 'GRAMMAR', 'GRAMPUS', 'GRANARY', 'GRANDAD', 'GRANDEE', 'GRANDMA', 'GRANDPA',
            'GRANITE', 'GRANOLA', 'GRANTED', 'GRANTEE', 'GRANTOR', 'GRANULE', 'GRAPHIC', 'GRAPPLE', 'GRATIFY', 'GRATING', 'GRAVELY',
            'GRAVITY', 'GRAYISH', 'GREASER', 'GREATLY', 'GRENADE', 'GRIDDED', 'GRIDDLE', 'GRIFFIN', 'GRILLED', 'GRIMACE', 'GRINDER',
            'GRIPING', 'GRISTLE', 'GRISTLY', 'GRITTER', 'GRIZZLE', 'GRIZZLY', 'GROCERY', 'GROMMET', 'GROOVED', 'GROUCHY', 'GROUNDS',
            'GROUPIE', 'GROWING', 'GRUBBER', 'GRUFFLY', 'GRUMBLE', 'GUARDED', 'GUIDING', 'GUILDER', 'GUMBOOT', 'GUNBOAT', 'GUNFIRE',
            'GUNSHOT', 'GUSHING', 'GUTLESS'
        ]
    },
    'H': {
        '3': [
            'HAG', 'HAM', 'HAP', 'HAT', 'HAW', 'HAY', 'HEM', 'HEN', 'HER', 'HEW', 'HEX', 'HEY', 'HIM', 'HIP', 'HIS', 'HIT', 'HOB', 'HOD',
            'HOE', 'HOG', 'HON', 'HOP', 'HOT', 'HOW', 'HUB', 'HUE', 'HUG', 'HUH', 'HUM', 'HUT'
        ],
        '4': [
            'HACK', 'HAFT', 'HAIL', 'HAIR', 'HAKE', 'HALE', 'HALF', 'HALL', 'HALO', 'HALT', 'HAND', 'HANG', 'HANK', 'HARD', 'HARE', 'HARK',
            'HARM', 'HARP', 'HART', 'HASH', 'HASP', 'HATE', 'HAUL', 'HAVE', 'HAWK', 'HAZE', 'HAZY', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT',
            'HECK', 'HEED', 'HEEL', 'HEFT', 'HEIR', 'HELL', 'HELM', 'HELP', 'HEMP', 'HERB', 'HERD', 'HERE', 'HERO', 'HERS', 'HICK', 'HIDE',
            'HIGH', 'HIKE', 'HILL', 'HILT', 'HIND', 'HINT', 'HIRE', 'HISS', 'HIVE', 'HOAX', 'HOBO', 'HOCK', 'HOLD', 'HOLE', 'HOLM', 'HOLY',
            'HOME', 'HONE', 'HONK', 'HOOD', 'HOOF', 'HOOK', 'HOOP', 'HOOT', 'HOPE', 'HOPS', 'HORN', 'HOSE', 'HOST', 'HOUR', 'HOWL', 'HUFF',
            'HUGE', 'HULA', 'HULK', 'HULL', 'HUMP', 'HUNG', 'HUNK', 'HUNT', 'HURL', 'HURT', 'HUSH', 'HUSK', 'HYMN', 'HYPE', 'HYPO'
        ],
        '5': [
            'HABIT', 'HAIKU', 'HAIRY', 'HALLO', 'HALVE', 'HANDY', 'HAPLY', 'HAPPY', 'HARDY', 'HAREM', 'HARPY', 'HARRY', 'HARSH',
            'HASTE', 'HASTY', 'HATCH', 'HAUNT', 'HAVEN', 'HAVOC', 'HAZEL', 'HEADS', 'HEADY', 'HEART', 'HEATH', 'HEAVE', 'HEAVY',
            'HEDGE', 'HEELS', 'HEFTY', 'HEIST', 'HELIX', 'HELLO', 'HELOT', 'HELVE', 'HENCE', 'HENNA', 'HERON', 'HERTZ', 'HEWER',
            'HIKER', 'HILLY', 'HINGE', 'HIPPY', 'HIPPO', 'HIRER', 'HITCH', 'HIVES', 'HOARD', 'HOARY', 'HOBBY', 'HOIST', 'HOKUM',
            'HOLLY', 'HOMER', 'HOMEY', 'HONEY', 'HONOR', 'HOOCH', 'HOOEY', 'HOOKY', 'HOOTS', 'HORDE', 'HORNY', 'HORSE', 'HOTEL',
            'HOTLY', 'HOUGH', 'HOUND', 'HOURI', 'HOUSE', 'HOVEL', 'HOVER', 'HOWDY', 'HUBBY', 'HUFFY', 'HULLO', 'HUMAN', 'HUMID',
            'HUMOR', 'HUMPH', 'HUMUS', 'HUNCH', 'HUNKS', 'HURRY', 'HUSKY', 'HUSSY', 'HUTCH', 'HYDRA', 'HYENA', 'HYMEN'
        ],
        '6': [
            'HACKER', 'HACKLE', 'HAGGIS', 'HAGGLE', 'HAIRDO', 'HALLOW', 'HALTER', 'HAMLET', 'HAMMER', 'HAMPER', 'HANDLE', 'HANGAR',
            'HANGER', 'HANKER', 'HANKIE', 'HANSOM', 'HAPPEN', 'HARASS', 'HARDEN', 'HARDLY', 'HARLOT', 'HARROW', 'HASSLE', 'HASTEN',
            'HATBOX', 'HATPIN', 'HATRED', 'HATTER', 'HAULER', 'HAUNCH', 'HAWKER', 'HAWSER', 'HAZARD', 'HEADED', 'HEADER', 'HEALER',
            'HEALTH', 'HEARSE', 'HEARTH', 'HEARTS', 'HEARTY', 'HEATED', 'HEATER', 'HEAVEN', 'HECKLE', 'HECTIC', 'HECTOR', 'HEIFER',
            'HEIGHT', 'HELIUM', 'HELMET', 'HELPER', 'HEMPEN', 'HERALD', 'HERBAL', 'HEREBY', 'HEREIN', 'HEREOF', 'HERESY', 'HERETO',
            'HERMIT', 'HERNIA', 'HEROIC', 'HEROIN', 'HERPES', 'HEYDAY', 'HIATUS', 'HICKEY', 'HIDDEN', 'HIDING', 'HIGHER', 'HIGHLY',
            'HIJACK', 'HIKING', 'HINDER', 'HIPPIE', 'HIPPED', 'HITHER', 'HOARSE', 'HOBBIT', 'HOBBLE', 'HOBNOB', 'HOCKEY', 'HOLDER',
            'HOLISM', 'HOLLER', 'HOLLOW', 'HOMAGE', 'HOMELY', 'HOMILY', 'HOMING', 'HOMINY', 'HONEST', 'HONKER', 'HONOUR', 'HONORS',
            'HOODED', 'HOODOO', 'HOOKAH', 'HOOKED', 'HOOKER', 'HOOPER', 'HOORAY', 'HOOTER', 'HOOVER', 'HOPPER', 'HORNED', 'HORNET',
            'HORRID', 'HORROR', 'HORSEY', 'HOSIER', 'HOSTEL', 'HOTBED', 'HOTKEY', 'HOTPOT', 'HOTTER', 'HOURLY', 'HOWLER', 'HOYDEN',
            'HUBBUB', 'HUBCAP', 'HUBRIS', 'HUDDLE', 'HUGELY', 'HUMANE', 'HUMBLE', 'HUMBUG', 'HUMMUS', 'HUMOUR', 'HUMPTY', 'HUNGER',
            'HUNGRY', 'HUNKER', 'HUNTER', 'HURDLE', 'HURRAH', 'HURRAY', 'HURTLE', 'HUSSAR', 'HUSTLE', 'HYAENA', 'HYBRID', 'HYMNAL',
            'HYPHEN', 'HYSSOP'
        ],
        '7': [
            'HABITAT', 'HACKLES', 'HACKNEY', 'HACKSAW', 'HADDOCK', 'HAGGARD', 'HAIRCUT', 'HAIRNET', 'HAIRPIN', 'HALBERD', 'HALFWAY',
            'HALIBUT', 'HALLWAY', 'HALOGEN', 'HALTING', 'HALYARD', 'HAMSTER', 'HANDBAG', 'HANDCAR', 'HANDFUL', 'HANDGUN', 'HANDILY',
            'HANDLER', 'HANDOUT', 'HANDSET', 'HANGDOG', 'HANGING', 'HANGMAN', 'HANGOUT', 'HAPLESS', 'HAPPILY', 'HARBOUR', 'HARDHAT',
            'HARDTOP', 'HARELIP', 'HARICOT', 'HARMFUL', 'HARMONY', 'HARNESS', 'HARPIST', 'HARPOON', 'HARRIER', 'HARVEST', 'HASHISH',
            'HASSOCK', 'HASTILY', 'HATBAND', 'HATCHET', 'HATEFUL', 'HAUGHTY', 'HAULAGE', 'HAULIER', 'HAWKING', 'HAWKISH', 'HAYCOCK',
            'HAYLOFT', 'HAYSEED', 'HAYWIRE', 'HEADING', 'HEADMAN', 'HEADSET', 'HEADWAY', 'HEALING', 'HEALTHY', 'HEARING', 'HEARKEN',
            'HEARSAY', 'HEARTEN', 'HEATHEN', 'HEATHER', 'HEATING', 'HEAVILY', 'HECKLER', 'HECTARE', 'HEEDFUL', 'HEIGHTS', 'HEINOUS',
            'HEIRESS', 'HELICAL', 'HELLCAT', 'HELLION', 'HELLISH', 'HELLUVA', 'HELPFUL', 'HELPING', 'HEMLINE', 'HEMLOCK', 'HEPARIN',
            'HEPATIC', 'HERBAGE', 'HERETIC', 'HEROICS', 'HEROISM', 'HERRING', 'HERSELF', 'HESSIAN', 'HEXAGON', 'HICKORY', 'HIDEOUS',
            'HIDEOUT', 'HIGHBOY', 'HIGHWAY', 'HILLOCK', 'HIMSELF', 'HIPBONE', 'HIPSTER', 'HIRSUTE', 'HISTORY', 'HOARSEN', 'HOBNAIL',
            'HOGGISH', 'HOGWASH', 'HOLDALL', 'HOLDING', 'HOLIDAY', 'HOLLAND', 'HOLSTER', 'HOMEBOY', 'HOMONYM', 'HONESTY', 'HONEYED',
            'HONOURS', 'HOPEFUL', 'HORIZON', 'HORMONE', 'HORRIFY', 'HOSANNA', 'HOSIERY', 'HOSPICE', 'HOSTAGE', 'HOSTESS', 'HOSTILE',
            'HOSTLER', 'HOTFOOT', 'HOTHEAD', 'HOTSHOT', 'HOTSPOT', 'HOUSING', 'HOWEVER', 'HOWLING', 'HULKING', 'HUMANLY', 'HUMDRUM',
            'HUMMOCK', 'HUNDRED', 'HUNKERS', 'HUNTING', 'HURDLER', 'HURDLES', 'HURLING', 'HURRIED', 'HURTFUL', 'HUSBAND', 'HUSTLER',
            'HYDRANT', 'HYDRATE', 'HYGIENE', 'HYPONYM'
        ]
    },
    'I': {
        '3': [
            'ICE', 'ICY', 'IFF', 'ILL', 'IMP', 'INK', 'INN', 'ION', 'IRE', 'IRK', 'ISM', 'ITS', 'IVY'
        ],
        '4': [
            'IAMB', 'IBID', 'IBIS', 'ICED', 'ICKY', 'ICON', 'IDEA', 'IDEM', 'IDLE', 'IDOL', 'IFFY', 'IMAM', 'INCH', 'INFO', 'INKY',
            'INST', 'INTO', 'IOTA', 'IRIS', 'IRON', 'ISLE', 'ITCH', 'ITEM'
        ],
        '5': [
            'ICING', 'IDEAL', 'IDIOM', 'IDIOT', 'IDLER', 'IDYLL', 'IGLOO', 'IMAGE', 'IMBUE', 'IMPEL', 'IMPLY', 'INANE', 'INAPT', 'INCUR',
            'INDEX', 'INDIE', 'INEPT', 'INERT', 'INFER', 'INFIX', 'INGOT', 'INLAY', 'INLET', 'INNER', 'INPUT', 'INSET', 'INTER', 'INTRO',
            'INURE', 'IRATE', 'IRONS', 'IRONY', 'ISLET', 'ISSUE', 'ITCHY', 'IVIED', 'IVORY'
        ],
        '6': [
            'IAMBIC', 'IAMBUS', 'IBIDEM', 'ICEBOX', 'ICEMAN', 'ICICLE', 'IDIOCY', 'IGNITE', 'IGNORE', 'IGUANA', 'IMMUNE', 'IMPACT',
            'IMPAIR', 'IMPALA', 'IMPALE', 'IMPART', 'IMPEDE', 'IMPISH', 'IMPORT', 'IMPOSE', 'IMPUGN', 'IMPURE', 'IMPUTE', 'INBORN',
            'INBRED', 'INCEST', 'INCISE', 'INCITE', 'INCOME', 'INDEED', 'INDENT', 'INDICT', 'INDIGO', 'INDOOR', 'INDUCE', 'INDUCT',
            'INFAMY', 'INFANT', 'INFECT', 'INFEST', 'INFIRM', 'INFLOW', 'INFLUX', 'INFORM', 'INFUSE', 'INGEST', 'INHALE', 'INHERE',
            'INJECT', 'INJURE', 'INJURY', 'INLAID', 'INLAND', 'INMATE', 'INMOST', 'INNATE', 'INSANE', 'INSECT', 'INSERT', 'INSIDE',
            'INSIST', 'INSOLE', 'INSTEP', 'INSULT', 'INSURE', 'INTACT', 'INTAKE', 'INTEND', 'INTENT', 'INTERN', 'INTONE', 'INTUIT',
            'INVADE', 'INVENT', 'INVERT', 'INVEST', 'INVITE', 'INVOKE', 'INWARD', 'IODINE', 'IONIZE', 'IREFUL', 'IRONIC', 'ISLAND',
            'ISOBAR', 'ISSUER', 'ITALIC', 'ITSELF'
        ],
        '7': [
            'ICEBERG', 'ICEBOAT', 'ICINESS', 'IDEALLY', 'IDIOTIC', 'IDOLIZE', 'IDYLLIC', 'IGNEOUS', 'IGNOBLE', 'ILLEGAL', 'ILLICIT',
            'ILLNESS', 'IMAGERY', 'IMAGINE', 'IMITATE', 'IMMENSE', 'IMMERSE', 'IMMORAL', 'IMPASSE', 'IMPEACH', 'IMPERIL', 'IMPETUS',
            'IMPIETY', 'IMPINGE', 'IMPIOUS', 'IMPLANT', 'IMPLODE', 'IMPLORE', 'IMPLIED', 'IMPOUND', 'IMPRESS', 'IMPRINT', 'IMPROVE',
            'IMPULSE', 'INANITY', 'INBOARD', 'INBOUND', 'INCENSE', 'INCISOR', 'INCLINE', 'INCLUDE', 'INCUBUS', 'INDEXED', 'INDOORS',
            'INDULGE', 'INERTIA', 'INEXACT', 'INFANCY', 'INFERNO', 'INFIDEL', 'INFLAME', 'INFLATE', 'INFLECT', 'INFLICT', 'INFUSER',
            'INGENUE', 'INGOING', 'INGRATE', 'INGRESS', 'INHABIT', 'INHALER', 'INHERIT', 'INHIBIT', 'INHUMAN', 'INITIAL', 'INJURED',
            'INKBLOT', 'INKLING', 'INKWELL', 'INNARDS', 'INQUEST', 'INQUIRE', 'INQUIRY', 'INROADS', 'INSHORE', 'INSIDER', 'INSIGHT',
            'INSIPID', 'INSOFAR', 'INSPIRE', 'INSTALL', 'INSTANT', 'INSTEAD', 'INSTILL', 'INSULAR', 'INSULIN', 'INSURED', 'INSURER',
            'INTEGER', 'INTENSE', 'INTERIM', 'INTRUDE', 'INVADER', 'INVALID', 'INVEIGH', 'INVERSE', 'INVOICE', 'INVOLVE', 'IONIZER',
            'IRIDIUM', 'IRKSOME', 'IRONING', 'ISOLATE', 'ISTHMUS', 'ITALICS', 'ITEMIZE', 'ITERATE'
        ]
    },
    'J': {
        '3': [
            'JAB', 'JAG', 'JAM', 'JAR', 'JAW', 'JAY', 'JET', 'JIB', 'JIG', 'JOB', 'JOG', 'JOT', 'JOY', 'JUG', 'JUT'
        ],
        '4': [
            'JACK', 'JADE', 'JAIL', 'JAMB', 'JANE', 'JAWS', 'JAZZ', 'JEEP', 'JEER', 'JELL', 'JERK', 'JESS', 'JEST', 'JIBE', 'JILT', 'JINX',
            'JIVE', 'JOHN', 'JOIN', 'JOKE', 'JOLT', 'JOSH', 'JOWL', 'JUDO', 'JUJU', 'JUMP', 'JUNK', 'JURY', 'JUST', 'JUTE'
        ],
        '5': [
            'JADED', 'JAMMY', 'JAPAN', 'JAUNT', 'JAZZY', 'JEANS', 'JEHAD', 'JELLY', 'JEMMY', 'JENNY', 'JERKY', 'JETTY', 'JEWEL', 'JIFFY',
            'JIHAD', 'JIMMY', 'JINGO', 'JOINT', 'JOIST', 'JOKER', 'JOLLY', 'JONAH', 'JONES', 'JOULE', 'JOUST', 'JUDGE', 'JUICE', 'JUICY',
            'JULEP', 'JUMBO', 'JUMPY', 'JUROR'
        ],
        '6': [
            'JABBER', 'JACKAL', 'JACKET', 'JAGGED', 'JAGUAR', 'JAILER', 'JALOPY', 'JANGLE', 'JARFUL', 'JARGON', 'JASPER', 'JAUNTY',
            'JEJUNE', 'JERKIN', 'JERSEY', 'JESTER', 'JIGGER', 'JIGGLE', 'JIGSAW', 'JINGLE', 'JINXED', 'JOBBER', 'JOCKEY', 'JOCOSE',
            'JOCUND', 'JOGGER', 'JOGGLE', 'JOHNNY', 'JOINER', 'JOJOBA', 'JOKING', 'JOSTLE', 'JOTTER', 'JOVIAL', 'JOYFUL', 'JOYOUS',
            'JUDDER', 'JUGGLE', 'JUJUBE', 'JUMBLE', 'JUMPER', 'JUNGLE', 'JUNIOR', 'JUNKET', 'JUNKIE', 'JURIST'
        ],
        '7': [
            'JACKASS', 'JACKDAW', 'JACKPOT', 'JANITOR', 'JASMINE', 'JAVELIN', 'JAWBONE', 'JAYWALK', 'JEALOUS', 'JELLIED', 'JELLIES',
            'JEWELER', 'JEWELRY', 'JITTERS', 'JITTERY', 'JOBBING', 'JOBLESS', 'JOCULAR', 'JOGGING', 'JOINERY', 'JOINTLY', 'JOLLILY',
            'JOLLITY', 'JOTTING', 'JOURNAL', 'JOURNEY', 'JOYLESS', 'JOYRIDE', 'JUBILEE', 'JUGGLER', 'JUGULAR', 'JUJITSU', 'JUKEBOX',
            'JUNIPER', 'JURYMAN', 'JUSTICE', 'JUSTIFY'
        ]
    },
    'K': {
        '3': [
            'KEG', 'KEN', 'KEY', 'KID', 'KIN', 'KIP', 'KIT'
        ],
        '4': [
            'KADI', 'KALE', 'KART', 'KEEL', 'KEEN', 'KEEP', 'KELP', 'KENO', 'KERB', 'KHAN', 'KICK', 'KILL', 'KILN', 'KILO', 'KILT', 'KIND',
            'KINE', 'KING', 'KINK', 'KIRK', 'KISS', 'KITE', 'KIWI', 'KNEE', 'KNIT', 'KNOB', 'KNOT', 'KNOW', 'KOHL', 'KOLO', 'KOOK'
        ],
        '5': [
            'KABOB', 'KANJI', 'KAPUT', 'KARAT', 'KARMA', 'KAYAK', 'KEEPS', 'KENDO', 'KETCH', 'KHAKI', 'KIDDY', 'KINKY', 'KIOSK', 'KNEEL',
            'KNIFE', 'KITTY', 'KNACK', 'KNAVE', 'KNEAD', 'KNEEL', 'KNELL', 'KNIFE', 'KNOCK', 'KNOLL', 'KNOWN', 'KOALA', 'KOOKY', 'KRAFT',
            'KUDOS', 'KULAK'
        ],
        '6': [
            'KAFTAN', 'KARATE', 'KEEPER', 'KELVIN', 'KELPIE', 'KENNEL', 'KERNEL', 'KETTLE', 'KEYPAD', 'KHAKIS', 'KIBOSH', 'KIDDIE',
            'KIDNAP', 'KIDNEY', 'KILLER', 'KILTED', 'KILTER', 'KIMONO', 'KINDLE', 'KINDLY', 'KINGLY', 'KIPPER', 'KISSER', 'KITSCH',
            'KITTEN', 'KLAXON', 'KNIGHT', 'KNOTTY', 'KOSHER'
        ],
        '7': [
            'KARAOKE', 'KARTING', 'KEEPING', 'KENNELS', 'KESTREL', 'KETCHUP', 'KEYHOLE', 'KEYLESS', 'KEYNOTE', 'KIBBUTZ', 'KICKING',
            'KICKOFF', 'KILLING', 'KILLJOY', 'KILOBIT', 'KINDRED', 'KINETIC', 'KINFOLK', 'KINGDOM', 'KINGPIN', 'KINSHIP', 'KINSMAN',
            'KINDRED', 'KITCHEN', 'KLEENEX', 'KNACKER', 'KNEECAP', 'KNITTER', 'KNOCKER', 'KNOTTED', 'KNOWING', 'KNUCKLE', 'KRYPTON',
            'KUMQUAT'
        ]
    },
    'L': {
        '3': [
            'LAB', 'LAD', 'LAG', 'LAM', 'LAP', 'LAV', 'LAW', 'LAX', 'LAY', 'LEA', 'LEG', 'LET', 'LIB', 'LID', 'LIE', 'LIP', 'LOB', 'LOG',
            'LOO', 'LOP', 'LOT', 'LOW', 'LUG', 'LUR', 'LUX'
        ],
        '4': [
            'LACK', 'LACE', 'LACK', 'LACY', 'LADS', 'LADY', 'LAIR', 'LAKE', 'LAMA', 'LAMB', 'LAME', 'LAMP', 'LAND', 'LANE', 'LANK', 'LARD',
            'LARK', 'LASH', 'LASS', 'LAST', 'LATE', 'LATH', 'LAUD', 'LAVA', 'LAWN', 'LAZE', 'LAZY', 'LEAD', 'LEAF', 'LEAK', 'LEAN', 'LEAP',
            'LEEK', 'LEER', 'LEES', 'LEFT', 'LEND', 'LENS', 'LESS', 'LEVY', 'LEWD', 'LIAR', 'LICK', 'LIDO', 'LIEN', 'LIEU', 'LIFE', 'LIFT',
            'LIKE', 'LILT', 'LILY', 'LIMB', 'LIME', 'LIMO', 'LIMP', 'LIMY', 'LINE', 'LINK', 'LINO', 'LINT', 'LION', 'LISP', 'LIST', 'LITE',
            'LIVE', 'LOAD', 'LOAF', 'LOAM', 'LOAN', 'LOBE', 'LOCH', 'LOCK', 'LOCO', 'LODE', 'LOFT', 'LOGO', 'LOGY', 'LOIN', 'LOLL', 'LONE',
            'LONG', 'LOOK', 'LOOM', 'LOON', 'LOOP', 'LOOT', 'LOPE', 'LORD', 'LORE', 'LOSE', 'LOSS', 'LOST', 'LOUD', 'LOUT', 'LOVE', 'LUAU',
            'LUBE', 'LUCK', 'LUDO', 'LUFF', 'LUGE', 'LULL', 'LULU', 'LUMP', 'LURE', 'LURK', 'LUSH', 'LUST', 'LUTE', 'LYNX', 'LYRE'
        ],
        '5': [
            'LABEL', 'LABOR', 'LACED', 'LADEN', 'LADLE', 'LAGER', 'LAITY', 'LANCE', 'LANKY', 'LAPEL', 'LAPSE', 'LARCH', 'LARGE', 'LARVA',
            'LASER', 'LASSO', 'LATCH', 'LATER', 'LATEX', 'LATHE', 'LATTE', 'LAUGH', 'LAYER', 'LEACH', 'LEAFY', 'LEAKY', 'LEARN', 'LEASE',
            'LEASH', 'LEAST', 'LEAVE', 'LEDGE', 'LEECH', 'LEFTY', 'LEGAL', 'LEGER', 'LEGGY', 'LEGIT', 'LEMMA', 'LEMON', 'LEMUR', 'LEPER',
            'LETUP', 'LEVEE', 'LEVEL', 'LEVER', 'LEXIS', 'LIANA', 'LIBEL', 'LIBRA', 'LICIT', 'LIEGE', 'LIFER', 'LIGHT', 'LIKEN', 'LILAC',
            'LIMBO', 'LIMEY', 'LIMIT', 'LINED', 'LINEN', 'LINER', 'LINES', 'LINKS', 'LIPID', 'LISTS', 'LITER', 'LITHE', 'LITRE', 'LIVEN',
            'LIVER', 'LIVID', 'LLAMA', 'LOATH', 'LOBBY', 'LOCAL', 'LOCUM', 'LOCUS', 'LODGE', 'LOESS', 'LOFTY', 'LOGIC', 'LOINS', 'LOLLY',
            'LONER', 'LOOKS', 'LOONY', 'LOOSE', 'LORRY', 'LOSER', 'LOTUS', 'LOUSE', 'LOUSY', 'LOVER', 'LOVEY', 'LOWER', 'LOWLY', 'LOYAL',
            'LUCID', 'LUCKY', 'LUCRE', 'LUMPY', 'LUNAR', 'LUNCH', 'LUNGE', 'LUNGS', 'LUPIN', 'LURCH', 'LUSTY', 'LYMPH', 'LYNCH', 'LYRIC'
        ],
        '6': [
            'LABIAL', 'LABILE', 'LABIUM', 'LABOUR', 'LACING', 'LACKEY', 'LACUNA', 'LADDER', 'LADDIE', 'LAGOON', 'LAMENT', 'LANCER',
            'LANCET', 'LANDAU', 'LANDED', 'LAPDOG', 'LAPSED', 'LAPTOP', 'LARIAT', 'LARYNX', 'LASSIE', 'LASTLY', 'LATELY', 'LATENT',
            'LATEST', 'LATHER', 'LATISH', 'LATTER', 'LAUNCH', 'LAUREL', 'LAVISH', 'LAWFUL', 'LAWMAN', 'LAWYER', 'LAYMAN', 'LAYOFF',
            'LAYOUT', 'LEADED', 'LEADEN', 'LEADER', 'LEAGUE', 'LEAVEN', 'LEAVES', 'LECHER', 'LEDGER', 'LEEWAY', 'LEGACY', 'LEGATE',
            'LEGATO', 'LEGEND', 'LEGION', 'LEGUME', 'LENDER', 'LENGTH', 'LENTIL', 'LESION', 'LESSEE', 'LESSEN', 'LESSER', 'LESSON',
            'LESSOR', 'LETHAL', 'LETTER', 'LEVITY', 'LIABLE', 'LIAISE', 'LIBIDO', 'LICHEN', 'LIGHTS', 'LIKELY', 'LIKING', 'LIMBER',
            'LIMPET', 'LIMPID', 'LINAGE', 'LINDEN', 'LINEAR', 'LINEUP', 'LINGER', 'LINING', 'LINKUP', 'LINTEL', 'LIQUID', 'LIQUOR',
            'LISTEN', 'LITANY', 'LITCHI', 'LITMUS', 'LITTER', 'LITTLE', 'LIVELY', 'LIVERY', 'LIVING', 'LIZARD', 'LOADED', 'LOAFER',
            'LOATHE', 'LOCALE', 'LOCATE', 'LOCKER', 'LOCKET', 'LOCUST', 'LODGER', 'LOGGER', 'LOGGIA', 'LOITER', 'LOLLOP', 'LONELY',
            'LONGER', 'LOOFAH', 'LOOKER', 'LOONEY', 'LOOSEN', 'LOOTER', 'LOSING', 'LOTION', 'LOUDLY', 'LOUNGE', 'LOUVER', 'LOUVRE',
            'LOVELY', 'LOVING', 'LUBBER', 'LUMBER', 'LUNACY', 'LUPINE', 'LUSTRE', 'LUXURY', 'LYRICS'
        ],
        '7': [
            'LABORED', 'LABORER', 'LACKING', 'LACONIC', 'LACQUER', 'LACTOSE', 'LADYBUG', 'LAGGARD', 'LAGGING', 'LAMAISM', 'LAMBADA',
            'LAMBKIN', 'LANDING', 'LANGUOR', 'LANYARD', 'LANOLIN', 'LANTERN', 'LAPWING', 'LARCENY', 'LARGELY', 'LASAGNA', 'LASHING',
            'LASTING', 'LATENCY', 'LATERAL', 'LATRINE', 'LATTICE', 'LAUNDER', 'LAUNDRY', 'LAWLESS', 'LAWSUIT', 'LAYAWAY', 'LAYERED',
            'LAYETTE', 'LAYOVER', 'LEADING', 'LEAFLET', 'LEANING', 'LEARNED', 'LEARNER', 'LEATHER', 'LEAVING', 'LECHERY', 'LECTERN',
            'LECTURE', 'LEEWARD', 'LEFTISM', 'LEFTIST', 'LEGALLY', 'LEGATEE', 'LEGIBLE', 'LEGIBLY', 'LEGLESS', 'LEGWORK', 'LEISURE',
            'LEMMING', 'LENDING', 'LENGTHY', 'LENIENT', 'LEONINE', 'LEOPARD', 'LEOTARD', 'LEPROSY', 'LEPROUS', 'LESBIAN', 'LETDOWN',
            'LETTERS', 'LETTING', 'LETTUCE', 'LEXICAL', 'LEXICON', 'LIAISON', 'LIBERAL', 'LIBERTY', 'LIBRARY', 'LICENCE', 'LICENSE',
            'LIFTING', 'LIGHTEN', 'LIGHTER', 'LIGHTLY', 'LIGNITE', 'LIKABLE', 'LIMEADE', 'LIMITED', 'LINCTUS', 'LINEAGE', 'LINEMAN',
            'LINGUAL', 'LINKAGE', 'LINKMAN', 'LINSEED', 'LIONESS', 'LIONIZE', 'LIPREAD', 'LIQUEFY', 'LIQUEUR', 'LITERAL', 'LITHIUM',
            'LITURGY', 'LIVABLE', 'LOADING', 'LOBSTER', 'LOCALLY', 'LODGING', 'LOGGING', 'LONGBOW', 'LONGING', 'LONGISH', 'LOOSELY',
            'LOTTERY', 'LOUNGER', 'LOURING', 'LOUTISH', 'LOVABLE', 'LOWLAND', 'LOYALTY', 'LOZENGE', 'LUCKILY', 'LUDDITE', 'LUFFING',
            'LUGGAGE', 'LUGSAIL', 'LULLABY', 'LUMBAGO', 'LUMPISH', 'LUNATIC', 'LUSTFUL', 'LUSTILY', 'LYRICAL'
        ]
    },
    'M': {
        '3': [
            'MAA', 'MAC', 'MAD', 'MAN', 'MAP', 'MAT', 'MAW', 'MAX', 'MAY', 'MEW', 'MIC', 'MID', 'MIX', 'MOB', 'MOG', 'MOM', 'MOO', 'MOP',
            'MOW', 'MUD', 'MUG', 'MUM'
        ],
        '4': [
            'MACE', 'MACH', 'MACK', 'MADE', 'MAID', 'MAIL', 'MAIM', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MALT', 'MAMA', 'MANE', 'MANY', 'MARC',
            'MARE', 'MARK', 'MASH', 'MASK', 'MASS', 'MAST', 'MATE', 'MATH', 'MATT', 'MAUL', 'MAXI', 'MAYO', 'MAZE', 'MEAD', 'MEAL', 'MEAN',
            'MEAT', 'MEEK', 'MEET', 'MEGA', 'MELT', 'MEMO', 'MEND', 'MENU', 'MEOW', 'MERE', 'MESH', 'MESS', 'METE', 'MEWS', 'MICA', 'MIDI',
            'MILD', 'MILE', 'MILK', 'MIND', 'MIEN', 'MIKE', 'MILD', 'MILE', 'MILK', 'MILL', 'MILT', 'MIME', 'MIND', 'MINE', 'MINI', 'MINK',
            'MINT', 'MIRE', 'MISS', 'MIST', 'MITE', 'MITT', 'MOAN', 'MOAT', 'MOCK', 'MODE', 'MOLD', 'MOLE', 'MOLL', 'MOLT', 'MONK', 'MONO',
            'MOOD', 'MOON', 'MOOR', 'MOOT', 'MOPE', 'MORE', 'MORN', 'MOSS', 'MOST', 'MOTE', 'MOTH', 'MOVE', 'MUCH', 'MUCK', 'MUFF', 'MULE',
            'MULL', 'MURK', 'MUSE', 'MUSH', 'MUSK', 'MUSS', 'MUST', 'MUTE', 'MUTT', 'MYTH'
        ],
        '5': [
            'MACAW', 'MACHO', 'MACRO', 'MADAM', 'MADLY', 'MAFIA', 'MAGIC', 'MAGMA', 'MAGUS', 'MAINS', 'MAIZE', 'MAJOR', 'MAKER', 'MAMBO',
            'MAMMA', 'MAMMY', 'MANGE', 'MANGO', 'MANGY', 'MANIA', 'MANIC', 'MANKY', 'MANLY', 'MANNA', 'MANOR', 'MAPLE', 'MARCH', 'MARGE',
            'MARRY', 'MARSH', 'MASON', 'MATCH', 'MATEY', 'MATHS', 'MATTE', 'MAUVE', 'MAVEN', 'MAVIS', 'MAXIM', 'MAYBE', 'MAYOR', 'MAZUR',
            'MEDIA', 'MERGE', 'METAL', 'MICRO', 'MIDST', 'MIGHT', 'MINCE', 'MINER', 'MODEL', 'MONEY', 'MOUND', 'MEALY', 'MEANS', 'MEANY',
            'MEATY', 'MECCA', 'MEDAL', 'MEDIA', 'MEDIC', 'MELON', 'MERCY', 'MERGE', 'MERIT', 'MERLE', 'MERRY', 'MESSY', 'METAL', 'METER',
            'METRE', 'METRO', 'MIAOW', 'MICRO', 'MIDGE', 'MIDST', 'MIGHT', 'MILKY', 'MIMIC', 'MINCE', 'MINER', 'MINGY', 'MINIM', 'MINOR',
            'MINUS', 'MIRTH', 'MISER', 'MISTY', 'MITER', 'MITRE', 'MIXED', 'MIXER', 'MODAL', 'MODEL', 'MODEM', 'MOGGY', 'MOGUL', 'MOIST',
            'MOLAR', 'MONAD', 'MONEY', 'MONTH', 'MOOCH', 'MOODY', 'MOONY', 'MOOSE', 'MOPED', 'MORAL', 'MOREL', 'MORES', 'MORON', 'MORPH',
            'MOSEY', 'MOSSY', 'MOTEL', 'MOTIF', 'MOTOR', 'MOTTO', 'MOULD', 'MOULT', 'MOUND', 'MOUNT', 'MOURN', 'MOUSE', 'MOUSY', 'MOUTH',
            'MOVER', 'MOVIE', 'MOWER', 'MUCKY', 'MUCUS', 'MUDDY', 'MUFTI', 'MUGGY', 'MULCH', 'MULCT', 'MULTI', 'MUMMY', 'MUMPS', 'MUNCH',
            'MURAL', 'MURKY', 'MUSHY', 'MUSIC', 'MUSKY', 'MUSTY', 'MUTED', 'MUZZY', 'MYRRH'
        ],
        '6': [
            'MACULA', 'MADAME', 'MADDEN', 'MADCAP', 'MADMAN', 'MAGGOT', 'MAGNET', 'MAGNUM', 'MAGPIE', 'MAHOUT', 'MAIDEN', 'MAILER',
            'MAINLY', 'MAKING', 'MALADY', 'MALICE', 'MALIGN', 'MALLET', 'MALLOW', 'MALTED', 'MAMMAL', 'MAMMON', 'MANAGE', 'MANEGE',
            'MANFUL', 'MANGER', 'MANGLE', 'MANIAC', 'MANIOC', 'MANNED', 'MANNER', 'MANQUE', 'MANTEL', 'MANTIS', 'MANTLE', 'MANUAL',
            'MANURE', 'MARACA', 'MARAUD', 'MARBLE', 'MARGIN', 'MARINA', 'MARINE', 'MARKED', 'MARKER', 'MARKET', 'MARKUP', 'MARMOT',
            'MAROON', 'MARRON', 'MARROW', 'MARSHY', 'MARTEN', 'MARTIN', 'MARTYR', 'MARVEL', 'MASCOT', 'MASHED', 'MASKED', 'MASSIF',
            'MASTER', 'MATING', 'MATINS', 'MATRIX', 'MATRON', 'MATTED', 'MATTER', 'MATURE', 'MAYDAY', 'MAYFLY', 'MAYHEM', 'MEADOW',
            'MEAGRE', 'MEANIE', 'MEASLY', 'MEDDLE', 'MEDIAL', 'MEDIAN', 'MEDIUM', 'MEDLEY', 'MEDUSA', 'MELLOW', 'MELODY', 'MEMBER',
            'MEMOIR', 'MEMORY', 'MENACE', 'MENAGE', 'MENHIR', 'MENIAL', 'MENSES', 'MENTAL', 'MENTOR', 'MERCER', 'MERELY', 'MERGER',
            'MERINO', 'MERLIN', 'MERMAN', 'MESCAL', 'METEOR', 'METHOD', 'METHYL', 'METRIC', 'METTLE', 'MIASMA', 'MICKEY', 'MICRON',
            'MIDDAY', 'MIDDEN', 'MIDDLE', 'MIDGET', 'MIDWAY', 'MIFFED', 'MIGHTY', 'MIKADO', 'MILDEW', 'MILDLY', 'MILIEU', 'MILKER',
            'MILLER', 'MILLET', 'MINCER', 'MINDER', 'MINGLE', 'MINING', 'MINION', 'MINNOW', 'MINUET', 'MINUTE', 'MIRAGE', 'MIRROR',
            'MISERY', 'MISFIT', 'MISHAP', 'MISLAY', 'MISSAL', 'MISSUS', 'MISTER', 'MISUSE', 'MITTEN', 'MOATED', 'MOBILE', 'MODERN',
            'MODEST', 'MODIFY', 'MODISH', 'MODULE', 'MOHAIR', 'MOIETY', 'MOLEST', 'MOLTEN', 'MOMENT', 'MONDAY', 'MONKEY', 'MOPPET',
            'MORALE', 'MORALS', 'MORASS', 'MORBID', 'MORGUE', 'MOROSE', 'MORROW', 'MORSEL', 'MORTAL', 'MORTAR', 'MOSAIC', 'MOSQUE',
            'MOSTLY', 'MOTHER', 'MOTION', 'MOTIVE', 'MOTLEY', 'MOULDY', 'MOUSER', 'MOUSSE', 'MOVIES', 'MOVING', 'MUDDLE', 'MUESLI',
            'MUFFIN', 'MUFFLE', 'MUGGER', 'MULISH', 'MULLED', 'MUMBLE', 'MURDER', 'MURMUR', 'MUSCLE', 'MUSEUM', 'MUSKET', 'MUSLIN',
            'MUSSEL', 'MUSTER', 'MUTANT', 'MUTATE', 'MUTINY', 'MUTTER', 'MUTTON', 'MUTUAL', 'MUZZLE', 'MYOPIA', 'MYOPIC', 'MYRIAD',
            'MYRTLE', 'MYSELF', 'MYSTIC', 'MYTHOS'
        ],
        '7': [
            'MACABRE', 'MACADAM', 'MACHETE', 'MACHINE', 'MACRAME', 'MADNESS', 'MAFIOSO', 'MAGGOTY', 'MAGICAL', 'MAGNATE', 'MAGNIFY',
            'MAILBOX', 'MAILING', 'MAILMAN', 'MAJESTY', 'MAKINGS', 'MALARIA', 'MALLARD', 'MALLING', 'MALWARE', 'MAMMOTH', 'MANACLE',
            'MANAGER', 'MANATEE', 'MANDALA', 'MANDATE', 'MANDREL', 'MANHOLE', 'MANHOOD', 'MANKIND', 'MANNERS', 'MANNISH', 'MANSARD',
            'MANSION', 'MAPPING', 'MARABOU', 'MARBLED', 'MARBLES', 'MARCHER', 'MARINER', 'MARITAL', 'MARKING', 'MARQUIS', 'MARRIED',
            'MARSHAL', 'MARTIAL', 'MARTINI', 'MASCARA', 'MASONIC', 'MASONRY', 'MASSAGE', 'MASSEUR', 'MASSIVE', 'MASTERY', 'MASTIFF',
            'MATADOR', 'MATTING', 'MATTOCK', 'MAUDLIN', 'MAUNDER', 'MAXILLA', 'MAXIMAL', 'MAXIMUM', 'MAXWELL', 'MAYORAL', 'MAYPOLE',
            'MEANDER', 'MEANING', 'MEASLES', 'MEASURE', 'MEDDLER', 'MEDIATE', 'MEDICAL', 'MEETING', 'MEGABIT', 'MEGATON', 'MELANGE',
            'MELANIN', 'MELODIC', 'MELTING', 'MEMENTO', 'MEMOIRS', 'MENDING', 'MENFOLK', 'MENORAH', 'MENTION', 'MERCURY', 'MERMAID',
            'MESSAGE', 'MESSIAH', 'METRICS', 'MICROBE', 'MIDLAND', 'MIDMOST', 'MIDRIFF', 'MIDTERM', 'MIDTOWN', 'MIDWEEK', 'MIDWIFE',
            'MIGRANT', 'MIGRATE', 'MILDEWY', 'MILEAGE', 'MILITIA', 'MILKING', 'MILKMAN', 'MILKSOP', 'MILLION', 'MIMESIS', 'MIMETIC',
            'MINARET', 'MINDFUL', 'MINDSET', 'MINERAL', 'MINIBUS', 'MINICAB', 'MINIMAL', 'MINIMUM', 'MINIVAN', 'MINSTER', 'MINUEND',
            'MINUTES', 'MIRACLE', 'MISCAST', 'MISDEED', 'MISERLY', 'MISFIRE', 'MISHEAR', 'MISLEAD', 'MISREAD', 'MISRULE', 'MISSILE',
            'MISSING', 'MISSION', 'MISTAKE', 'MISTIME', 'MITOSIS', 'MIXTURE', 'MOBSTER', 'MOCKERY', 'MODESTY', 'MODICUM', 'MODULAR',
            'MODULUS', 'MOISTEN', 'MOLLIFY', 'MOLLUSC', 'MOLLUSK', 'MONARCH', 'MONEYED', 'MONGREL', 'MONIKER', 'MONITOR', 'MONKISH',
            'MONOCLE', 'MONSOON', 'MONSTER', 'MONTAGE', 'MONTHLY', 'MOONLIT', 'MOORING', 'MOORISH', 'MORALLY', 'MORDANT', 'MOREISH',
            'MORNING', 'MOROCCO', 'MORONIC', 'MORTIFY', 'MORTISE', 'MOTTLED', 'MOULDER', 'MOUNTED', 'MOURNER', 'MOVABLE', 'MUDFLAP',
            'MUDPACK', 'MUEZZIN', 'MUFFLER', 'MUGGING', 'MUGSHOT', 'MULLION', 'MUMMIFY', 'MUNDANE', 'MURRAIN', 'MUSETTE', 'MUSICAL',
            'MUSTANG', 'MUSTARD', 'MUTABLE', 'MYSTERY', 'MYSTIFY'
        ]
    },
    'N': {
        '3': [
            'NAB', 'NAG', 'NAN', 'NAP', 'NAY', 'NEE', 'NET', 'NEW', 'NIB', 'NIL', 'NIP', 'NIT', 'NIX', 'NOD', 'NOR', 'NOT', 'NOW', 'NUB',
            'NUN', 'NUT'
        ],
        '4': [
            'NAFF', 'NAIL', 'NAME', 'NAPE', 'NARC', 'NARK', 'NARY', 'NAVE', 'NAVY', 'NEAR', 'NEAT', 'NECK', 'NEED', 'NEON', 'NERD', 'NESS',
            'NEST', 'NETT', 'NEWS', 'NEWT', 'NEXT', 'NICE', 'NICK', 'NIFF', 'NIGH', 'NINE', 'NODE', 'NONE', 'NOOK', 'NOON', 'NOPE', 'NORM',
            'NOSE', 'NOSH', 'NOSY', 'NOTE', 'NOUN', 'NOUS', 'NUDE', 'NUKE', 'NULL', 'NUMB', 'NUTS'
        ],
        '5': [
            'NABOB', 'NACRE', 'NADIR', 'NAIAD', 'NAIVE', 'NAKED', 'NANNY', 'NAPPY', 'NARKY', 'NASAL', 'NASTY', 'NATAL', 'NATCH', 'NATTY',
            'NAVAL', 'NAVEL', 'NAVVY', 'NEDDY', 'NEEDS', 'NEEDY', 'NEIGH', 'NELLY', 'NERVE', 'NERVY', 'NETTY', 'NEVER', 'NEWLY', 'NEWSY',
            'NEXUS', 'NICHE', 'NIECE', 'NIFFY', 'NIGHT', 'NINJA', 'NINNY', 'NINTH', 'NIPPY', 'NITRE', 'NOBLE', 'NOBLY', 'NODAL', 'NOISE',
            'NOISY', 'NOMAD', 'NONCE', 'NOOSE', 'NORTH', 'NOSEY', 'NOTCH', 'NOTED', 'NOVEL', 'NUDGE', 'NURSE', 'NUTTY', 'NYLON', 'NYMPH'
        ],
        '6': [
            'NACHOS', 'NAMELY', 'NAPALM', 'NAPKIN', 'NARROW', 'NATION', 'NATIVE', 'NATTER', 'NATURE', 'NAUGHT', 'NAUSEA', 'NEARBY',
            'NEARLY', 'NEBULA', 'NECTAR', 'NEEDLE', 'NEGATE', 'NEPHEW', 'NEREID', 'NERVES', 'NESTLE', 'NETHER', 'NETTLE', 'NEURAL',
            'NEURON', 'NEUTER', 'NEWBIE', 'NIBBLE', 'NICELY', 'NICETY', 'NICKEL', 'NICKER', 'NIGGLE', 'NIMBLE', 'NIMBUS', 'NINETY',
            'NIPPER', 'NIPPLE', 'NITWIT', 'NOBBLE', 'NOBODY', 'NODULE', 'NOGGIN', 'NONCOM', 'NOODLE', 'NORMAL', 'NOTARY', 'NOTICE',
            'NOTIFY', 'NOTION', 'NOUGAT', 'NOUGHT', 'NOVICE', 'NOZZLE', 'NUANCE', 'NUBILE', 'NUDISM', 'NUDIST', 'NUDITY', 'NUGGET',
            'NUMBER', 'NUNCIO', 'NUTMEG', 'NUTRIA', 'NUTTER', 'NUZZLE', 'NYLONS'
        ],
        '7': [
            'NAGGING', 'NAGWARE', 'NAIVETY', 'NARRATE', 'NASCENT', 'NATURAL', 'NAUGHTY', 'NEBULAR', 'NECKTIE', 'NEEDFUL', 'NEGLECT',
            'NEGROID', 'NEITHER', 'NEMESIS', 'NERVOUS', 'NETBALL', 'NETIZEN', 'NETTING', 'NETWORK', 'NEUTRAL', 'NEUTRON', 'NEWBORN',
            'NEWNESS', 'NEWSMAN', 'NIGGARD', 'NIGHTIE', 'NIGHTLY', 'NINEPIN', 'NIPPERS', 'NITRATE', 'NOISILY', 'NOISOME', 'NOMADIC',
            'NOMINAL', 'NONPLUS', 'NOONDAY', 'NOSEBAG', 'NOSEGAY', 'NOSTRIL', 'NOSTRUM', 'NOTABLE', 'NOTABLY', 'NOTELET', 'NOTEPAD',
            'NOTHING', 'NOTIONS', 'NOURISH', 'NOVELLA', 'NOVELTY', 'NOWHERE', 'NOXIOUS', 'NUCLEAR', 'NUCLEUS', 'NULLIFY', 'NULLITY',
            'NUMBERS', 'NUMERAL', 'NUNNERY', 'NUPTIAL', 'NURSERY', 'NURSING', 'NURTURE', 'NUTCASE'
        ]
    },
    'O': {
        '3': [
            'OAK', 'OFF', 'ONE', 'OUR', 'OUT', 'OWL'
        ],
        '4': [
            'OBEY', 'OMIT', 'ONCE', 'ONLY', 'OPEN', 'OURS', 'OVER'
        ],
        '5': [
            'OAKEN', 'OFFER', 'OPTION', 'ORDER', 'OTHER', 'OUGHT', 'OUNCE'
        ],
        '6': [
            'OCCUPY', 'OFFEND', 'OFFICE', 'ONLINE', 'ONWARD'
        ],
        '7': [
            'OFFICER', 'OFFLINE', 'ONGOING'
        ]
    },
    'P': {
        '3': [
            'PAY', 'PEN', 'PIN', 'PIT', 'POP', 'PUB', 'PUN', 'PUT'
        ],
        '4': [
            'PACK', 'PAGE', 'PAIR', 'PART', 'PATH', 'PEND', 'PICK', 'PINK', 'PLAY', 'POEM', 'POET', 'POND', 'POOR', 'POST', 'PUKE', 'PULL',
            'PUMP', 'PUNK', 'PUSH'
        ],
        '5': [
            'PAINT', 'PAPER', 'PARTY', 'PAUSE', 'PENNY', 'PHONE', 'PIANO', 'PLACE', 'PLAIN', 'PLANT', 'PLUCK', 'POINT', 'POUND', 'POWER',
            'PRIDE', 'PRINT', 'PROUD', 'PRUNE', 'PULSE', 'PUNCH', 'PUPPY', 'PUSHY'
        ],
        '6': [
            'PALACE', 'PARENT', 'PLAYER', 'PENCIL', 'PEOPLE', 'PERIOD', 'PERSON', 'PIRATE', 'PLEASE', 'POCKET', 'POINTY', 'POLICY',
            'POTION', 'PUBLIC', 'PUNISH'
        ],
        '7': [
            'PACKAGE', 'PAINTER', 'PATTERN', 'PENDANT', 'PERFECT', 'PERFORM', 'PICTURE', 'PLEASED', 'PORTION', 'PREMIUM', 'PREPARE', 'PRIMARY', 'PRINTER',
            'PRIVACY', 'PROCESS', 'PRODUCT', 'PROFILE', 'PROJECT', 'PROMOTE', 'PUBLISH', 'PUNGENT'
        ]
    },
    'Q': {
        '3': [],
        '4': [
            'QUAD', 'QUAY', 'QUIT', 'QUIZ'
        ],
        '5': [
            'QUEEN', 'QUEER', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUIRK', 'QUITE', 'QUOTA', 'QUOTE'
        ],
        '6': [
            'QUAINT', 'QUARRY'
        ],
        '7': [
            'QUALITY', 'QUARREL', 'QUARTER'
        ]
    },
    'R': {
        '3': [
            'RAM', 'RAP', 'RAT', 'RAW', 'RAY', 'RED', 'RID', 'ROB', 'ROW', 'RUG', 'RUM', 'RUN'
        ],
        '4': [
            'RACE', 'RACK', 'RAIL', 'RAIN', 'RANK', 'RAPE', 'RARE', 'RASH', 'RATE', 'RAVE', 'RELY', 'RENT', 'REST', 'RICH', 'RIDE', 'RING',
            'RISE', 'ROAD', 'ROAM', 'ROCK', 'ROLL', 'ROOM', 'ROSE', 'RUDE', 'RULE', 'RUNE', 'RUSH'
        ],
        '5': [
            'RADAR', 'RADIO', 'RAINY', 'RAISE', 'RAZOR', 'READY', 'REBEL', 'RENEW', 'REPLY', 'RETRY', 'RINSE', 'RIVER', 'ROBIN', 'ROGUE',
            'ROUND', 'ROUTE', 'ROYAL', 'RULER'
        ],
        '6': [
            'RABBIT', 'RARELY', 'RATHER', 'REBOOT', 'RECIPE', 'REMIND', 'RELATE', 'REMOVE', 'RENAME', 'RENDER', 'RESIST', 'REVEAL',
            'ROUTER', 'ROBBER', 'RUNNER', 'RHYTHM'
        ],
        '7': [
            'RAILWAY', 'RAINBOW', 'RECEIPT', 'REGULAR', 'RESTART', 'REVERSE', 'ROBBERY'
        ]
    },
    'S': {
        '3': [
            'SAP', 'SAY', 'SEA', 'SEE', 'SET', 'SEX', 'SHY', 'SIN', 'SIR', 'SIX', 'SIT', 'SKY', 'SUM', 'SUN'
        ],
        '4': [
            'SACK', 'SAFE', 'SAIL', 'SALT', 'SAFE', 'SALE', 'SAME', 'SAND', 'SANE', 'SAVE', 'SEAL', 'SEAT', 'SEEK', 'SELF', 'SELL', 'SEND',
            'SHOW', 'SHUT', 'SICK', 'SIDE', 'SIGN', 'SING', 'SINK', 'SIRE', 'SITE', 'SKIN', 'SLAM', 'SNOW', 'SOAP', 'SOFT', 'SOME', 'SONG',
            'SOUP', 'SOUR', 'SPIT', 'STAG', 'STAR', 'STEW', 'STOP', 'SUIT'
        ],
        '5': [
            'SABER', 'SAINT', 'SALTY', 'SAPPY', 'SAVOR', 'SAVVY', 'SCARE', 'SCARF', 'SCARY', 'SCREW', 'SENSE', 'SERVE', 'SEVEN', 'SHAKE',
            'SHAME', 'SHARK', 'SHARP', 'SHELL', 'SHINE', 'SHIFT', 'SHINE', 'SHIRE', 'SHIRT', 'SHOCK', 'SHOES', 'SHOOT', 'SHORT', 'SHOUT',
            'SIGHT', 'SILLY', 'SIXTY', 'SKIRT', 'SKULL', 'SLACK', 'SLAVE', 'SLEEP', 'SLIDE', 'SLIME', 'SLIMY', 'SMART', 'SMELL', 'SMILE',
            'SNAKE', 'SNEAK', 'SNOWY', 'SOCKS', 'SOLID', 'SOUND', 'SPELL', 'SPICE', 'SPICY', 'SPOON', 'SPRAY', 'STAGE', 'STAIN', 'STALE',
            'START', 'STATE', 'STEAL', 'STEAM', 'STEEL', 'STING', 'STICK', 'STING', 'STINK', 'STOCK', 'STORE', 'STORM', 'STUDY', 'STYLE',
            'SUNNY', 'SWAMP', 'SWEAR', 'SWEAT', 'SWEET', 'SWIFT', 'SWING'
        ],
        '6': [
            'SAILOR', 'SAMPLE', 'SANITY', 'SAVAGE', 'SAVIOR', 'SAVOUR', 'SAYING', 'SCARED', 'SCHOOL', 'SCREAM', 'SCREEN', 'SEARCH',
            'SEASON', 'SECOND', 'SELECT', 'SELFIE', 'SENDER', 'SENSOR', 'SHIVER', 'SHORTS', 'SHOULD', 'SHOWER', 'SHRIMP', 'SHRINK',
            'SHRINE', 'SICKEN', 'SILVER', 'SINGER', 'SINGLE', 'SISTER', 'SKINNY', 'SLEEPY', 'SLOPPY', 'SMOOTH', 'SNEEZE', 'SOURCE',
            'SPIRIT', 'SPRING', 'STARRY', 'STATUS', 'STINKY', 'STORMY', 'STREAM', 'STREET', 'STRIKE', 'STRONG', 'STUPID', 'SUMMER',
            'SUNDAY', 'SWITCH', 'SYSTEM'
        ],
        '7': [
            'SAVIOUR', 'SERVICE', 'SETTING', 'SEVENTY', 'SHELTER', 'SHOOTER', 'STATION', 'STOMACH', 'STRANGE', 'STUPEFY', 'SUCCESS',
            'STYLISH'
        ]
    },
    'T': {
        '3': [
            'TAN', 'TAP', 'TEA', 'TEN', 'THE', 'TIE', 'TIN', 'TIT', 'TOE', 'TOP', 'TRY', 'TWO'
        ],
        '4': [
            'TAIL', 'TAKE', 'TALE', 'TAME', 'TANK', 'TAPE', 'TASK', 'TEAL', 'TEAM', 'TEAR', 'TENT', 'THEM', 'THEN', 'THIN', 'TILE', 'TILL',
            'TIME', 'TOOL', 'TRAM', 'TRAY', 'TREE', 'TRIP', 'TRUE', 'TUBE', 'TUNE', 'TYPE'
        ],
        '5': [
            'TABLE', 'TALON', 'TASTE', 'TEACH', 'THANK', 'THEFT', 'THEIR', 'THERE', 'THICK', 'THIEF', 'THING', 'THINK', 'THORN', 'THREE',
            'THROW', 'TIGER', 'TIMER', 'TIRED', 'TODAY', 'TOOTH', 'TOUCH', 'TRACE', 'TRAIL', 'TRAIN', 'TRAMP', 'TREND', 'TRIAL', 'TRIBE',
            'TROOP', 'TRUCK', 'TRUTH', 'TWICE'
        ],
        '6': [
            'TACKLE', 'THANKS', 'THEIRS', 'THINGY', 'THIRTY', 'THRIVE', 'TOILET', 'TOMATO', 'TOUCHY', 'TRENDY', 'TRIBAL', 'TWELVE',
            'TWENTY'
        ],
        '7': [
            'TEACHER', 'TEARFUL', 'TERRIER', 'THOUGHT', 'TODDLER', 'TONIGHT', 'TRAINER', 'TRINITY', 'TROOPER', 'TRUMPET', 'TUESDAY'
        ]
    },
    'U': {
        '3': [
            'URN', 'USE'
        ],
        '4': [
            'UNIT', 'URGE', 'USER'
        ],
        '5': [
            'UNCLE', 'UNDER', 'UNFIT', 'UNITE', 'UNTIE', 'UNTIL', 'UPPER', 'USAGE'
        ],
        '6': [
            'UNABLE', 'UNCLEAN', 'UNCLEAR', 'UNFAIR', 'UNFURL', 'UPDATE'
        ],
        '7': [
            'UNAWARE', 'UNCANNY', 'UNCOVER', 'UNDERGO', 'UTILITY'
        ]
    },
    'V': {
        '3': [
            'VAN', 'VET', 'VOW'
        ],
        '4': [
            'VALE', 'VAMP', 'VANE', 'VARY', 'VASE', 'VAST', 'VERB', 'VERY', 'VOID'
        ],
        '5': [
            'VAGUE', 'VALID', 'VALOR', 'VALUE', 'VALVE', 'VIDEO', 'VIRAL', 'VIRUS', 'VISIT', 'VOWEL'
        ],
        '6': [
            'VACUUM', 'VALLEY', 'VALOUR', 'VANISH', 'VANITY', 'VERIFY', 'VERSUS', 'VESSEL', 'VIOLET', 'VIOLIN', 'VOLUME'
        ],
        '7': [
            'VAGRANT', 'VALIANT', 'VAMPIRE', 'VARIANT', 'VARIOUS', 'VISIBLE'
        ]
    },
    'W': {
        '3': [
            'WAN', 'WAR', 'WAS', 'WAY', 'WEB', 'WET', 'WHY', 'WIG', 'WIN'
        ],
        '4': [
            'WAIL', 'WAIT', 'WAND', 'WANE', 'WANT', 'WARD', 'WARM', 'WARN', 'WASH', 'WAVE', 'WAVY', 'WEAK', 'WEAN', 'WEAR', 'WELL', 'WERE',
            'WHAT', 'WHEN', 'WHOM', 'WILL', 'WIND', 'WING', 'WIRE', 'WISH', 'WITH', 'WORD', 'WORK'
        ],
        '5': [
            'WATER', 'WAIST', 'WEARY', 'WEAVE', 'WHALE', 'WHERE', 'WHICH', 'WHILE', 'WHINE', 'WHITE', 'WHOLE', 'WHOSE', 'WIDOW', 'WIELD',
            'WINCE', 'WINDY', 'WITCH', 'WOMAN', 'WORLD', 'WORSE', 'WORST', 'WOULD', 'WOUND', 'WRING', 'WRITE', 'WRONG'
        ],
        '6': [
            'WAITER', 'WEALTH', 'WEAPON', 'WEASEL', 'WEIGHT', 'WICKED', 'WINDOW', 'WINNER', 'WINTER', 'WITHER', 'WRAITH', 'WRITER',
            'WRITHE'
        ],
        '7': [
            'WARLOCK', 'WARLORD', 'WARNING', 'WEBPAGE', 'WEALTHY', 'WEATHER', 'WISHFUL', 'WHISPER', 'WOUNDED'
        ]
    },
    'Y': {
        '3': [
            'YEA', 'YES', 'YET', 'YOU'
        ],
        '4': [
            'YEAH', 'YEAR', 'YELL', 'YELP', 'YOUR', 'YUCK'
        ],
        '5': [
            'YEARN', 'YEAST', 'YIELD', 'YOUNG', 'YOURS', 'YUMMY'
        ],
        '6': [
            'YEARLY', 'YELLOW'
        ],
        '7': []
    },
    'Z': {
        '3': [
            'ZOO'
        ],
        '4': [
            'ZANY', 'ZEAL', 'ZERO', 'ZONE', 'ZOOM'
        ],
        '5': [],
        '6': [
            'ZEALOT', 'ZENITH', 'ZIGZAG', 'ZODIAC'
        ],
        '7': []
    }
};
